import type { Language } from './i18n';

type OperatorUiKey =
  | 'kpi.vs_last_week'
  | 'overview.last_data'
  | 'overview.badge.stripe_enabled'
  | 'overview.badge.local_sales_active'
  | 'overview.badge.printer_telemetry'
  | 'overview.partial_data'
  | 'overview.kiosk.revenue_today'
  | 'overview.kiosk.photos_sold_today'
  | 'overview.kiosk.photo_paper'
  | 'overview.kiosk.photos_sold_month'
  | 'overview.kiosk.revenue_month'
  | 'overview.kiosk.photos_sold_total'
  | 'overview.online_revenue'
  | 'overview.local_revenue'
  | 'overview.transactions'
  | 'overview.errors'
  | 'overview.warnings'
  | 'overview.paper_remaining'
  | 'overview.print_count'
  | 'overview.widget.last_activity'
  | 'overview.widget.open_system_health'
  | 'overview.widget.data_files_scanned'
  | 'overview.widget.recognized_ops_files'
  | 'overview.widget.open_operations'
  | 'overview.widget.users'
  | 'overview.widget.open_users'
  | 'overview.widget.photos'
  | 'overview.widget.open_photos'
  | 'overview.widget.active_attractions'
  | 'overview.widget.conversion_today'
  | 'overview.widget.sold_per_ride'
  | 'overview.widget.rides_today'
  | 'overview.kiosk.chart_title'
  | 'overview.kiosk.chart_subtitle'
  | 'overview.kiosk.chart_revenue'
  | 'overview.flow.title'
  | 'overview.flow.subtitle'
  | 'overview.flow.payment_success'
  | 'overview.activity.title'
  | 'overview.activity.subtitle'
  | 'overview.activity.none'
  | 'overview.activity.cleared'
  | 'overview.activity.support'
  | 'overview.activity.stripe'
  | 'overview.activity.ops'
  | 'overview.activity.clear'
  | 'overview.recent_transactions'
  | 'overview.recent_transactions.none'
  | 'overview.recent_transactions.show_less'
  | 'overview.recent_transactions.show_all'
  | 'overview.kiosk.sale_title'
  | 'overview.kiosk.sale_claimed'
  | 'overview.kiosk.sale_unknown'
  | 'overview.support_reply'
  | 'overview.online_payment'
  | 'overview.local_transaction'
  | 'overview.local_sale'
  | 'overview.stripe_payment_fallback'
  | 'revenue.subtitle_unified'
  | 'revenue.partial_available'
  | 'revenue.no_feed_title'
  | 'revenue.no_feed_desc'
  | 'revenue.kiosk.title'
  | 'revenue.kiosk.desc'
  | 'revenue.kpi.today'
  | 'revenue.kpi.last_7_days'
  | 'revenue.kpi.this_month'
  | 'revenue.kpi.total_since_records'
  | 'revenue.kpi.rides_today'
  | 'revenue.kpi.camera_captures_today'
  | 'revenue.kpi.conversion_today'
  | 'revenue.kpi.sold_per_ride'
  | 'revenue.kpi.total_revenue'
  | 'revenue.kpi.total_transactions'
  | 'revenue.section.revenue'
  | 'revenue.section.daily_machine'
  | 'revenue.section.hourly'
  | 'revenue.tab.total'
  | 'revenue.tab.today'
  | 'revenue.tab.yesterday'
  | 'revenue.tab.other_day'
  | 'revenue.previous_day'
  | 'revenue.next_day'
  | 'revenue.select_day'
  | 'revenue.day_revenue'
  | 'revenue.photos_sold'
  | 'revenue.loading'
  | 'revenue.no_sales'
  | 'revenue.legend.revenue'
  | 'revenue.legend.rides'
  | 'revenue.daily_overview'
  | 'revenue.no_sales_data'
  | 'revenue.table.day'
  | 'revenue.table.sold'
  | 'revenue.table.rides'
  | 'revenue.table.rate'
  | 'revenue.table.revenue'
  | 'revenue.online_commerce.title'
  | 'revenue.online_commerce.subtitle'
  | 'revenue.online_commerce.confirmed_revenue'
  | 'revenue.online_commerce.successful_payments'
  | 'revenue.local_operations.title'
  | 'revenue.local_operations.subtitle'
  | 'revenue.local_operations.confirmed_revenue'
  | 'revenue.local_operations.detected_unconfirmed'
  | 'revenue.local_operations.unknown_signals'
  | 'revenue.trend.title'
  | 'revenue.trend.subtitle'
  | 'revenue.breakdown.title'
  | 'revenue.breakdown.subtitle'
  | 'revenue.signals.title'
  | 'revenue.signals.payment_attempts'
  | 'revenue.signals.success_rate'
  | 'revenue.signals.cancel_rate'
  | 'revenue.signals.cash_transactions'
  | 'revenue.signals.terminal_transactions'
  | 'revenue.signals.unconfirmed_local_sales'
  | 'revenue.signals.unknown_local_amounts'
  | 'revenue.legend.online'
  | 'revenue.legend.local'
  | 'revenue.cash'
  | 'revenue.terminal'
  | 'revenue.detected_unconfirmed'
  | 'revenue.local_display.detected'
  | 'revenue.local_display.unknown'
  | 'revenue.local_display.confirmed_only'
  | 'revenue.local_display.detected_only'
  | 'revenue.local_display.unknown_only'
  | 'revenue.local_display.none_yet'
  | 'purchases.subtitle_kiosk'
  | 'purchases.subtitle_unified'
  | 'purchases.partial_available'
  | 'purchases.table.source'
  | 'purchases.table.customer_device'
  | 'purchases.table.payment'
  | 'purchases.table.description'
  | 'purchases.source.online'
  | 'purchases.source.local'
  | 'purchases.source.kiosk'
  | 'purchases.source.automaton'
  | 'purchases.customer.stripe'
  | 'purchases.customer.local_device'
  | 'purchases.customer.unknown'
  | 'purchases.status.claimed'
  | 'purchases.amount.detected'
  | 'purchases.amount.none'
  | 'purchases.filter.all'
  | 'purchases.filter.online'
  | 'purchases.filter.local'
  | 'purchases.description.kiosk_bought'
  | 'purchases.description.kiosk_claimed'
  | 'photos.error_loading'
  | 'photos.data_unavailable'
  | 'photos.for_day'
  | 'photos.for_day_desc'
  | 'photos.previous_day'
  | 'photos.next_day'
  | 'photos.today'
  | 'photos.subtitle.day_captures'
  | 'photos.subtitle.sold_total'
  | 'photos.subtitle.on_that_day'
  | 'photos.expired'
  | 'photos.conversion_chart'
  | 'photos.not_purchased'
  | 'photos.rides_without_purchase'
  | 'photos.of_rides'
  | 'photos.by_attraction.none'
  | 'photos.by_attraction.captures'
  | 'photos.by_attraction.sold'
  | 'photos.email_capture'
  | 'photos.email_capture.buyers'
  | 'photos.email_capture.none'
  | 'photos.browser.title'
  | 'photos.browser.refresh'
  | 'photos.browser.search_code'
  | 'photos.browser.search'
  | 'photos.browser.reset'
  | 'photos.browser.none'
  | 'photos.browser.status.purchased'
  | 'photos.browser.status.available'
  | 'photos.browser.photo_alt'
  | 'photos.browser.selected_alt'
  | 'photos.browser.copy_claim'
  | 'photos.browser.copy_image'
  | 'photos.browser.copied'
  | 'photos.browser.claim_explainer'
  | 'photos.browser.select_prompt';

type OperatorUiVars = Record<string, string | number>;

const copy: Record<Language, Record<OperatorUiKey, string>> = {
  de: {
    'kpi.vs_last_week': 'vs letzte Woche',
    'overview.last_data': 'Letzte Daten {time}',
    'overview.badge.stripe_enabled': 'Stripe aktiv',
    'overview.badge.local_sales_active': 'Lokale Verkäufe aktiv',
    'overview.badge.printer_telemetry': 'Drucker-Telemetrie',
    'overview.partial_data': 'Einige Datenquellen sind derzeit nicht verfügbar.',
    'overview.kiosk.revenue_today': 'Umsatz heute',
    'overview.kiosk.photos_sold_today': 'Fotos verkauft heute',
    'overview.kiosk.photo_paper': 'Fotopapier',
    'overview.kiosk.photos_sold_month': 'Fotos verkauft (Monat)',
    'overview.kiosk.revenue_month': 'Umsatz (Monat)',
    'overview.kiosk.photos_sold_total': 'Fotos verkauft (gesamt)',
    'overview.online_revenue': 'Online-Umsatz',
    'overview.local_revenue': 'Lokaler Umsatz',
    'overview.transactions': 'Transaktionen',
    'overview.errors': 'Fehler',
    'overview.warnings': 'Warnungen',
    'overview.paper_remaining': 'Papier verbleibend',
    'overview.print_count': 'Anzahl Drucke',
    'overview.widget.last_activity': 'Letzte Aktivität',
    'overview.widget.open_system_health': 'Systemzustand öffnen',
    'overview.widget.data_files_scanned': 'Datendateien gescannt',
    'overview.widget.recognized_ops_files': 'Erkannte Betriebsdateien',
    'overview.widget.open_operations': 'Operations öffnen',
    'overview.widget.users': 'Benutzer',
    'overview.widget.open_users': 'Benutzer öffnen',
    'overview.widget.photos': 'Fotos',
    'overview.widget.open_photos': 'Fotos öffnen',
    'overview.widget.active_attractions': 'Aktive Attraktionen',
    'overview.widget.conversion_today': 'Conversion heute',
    'overview.widget.sold_per_ride': 'Verkauft je Fahrt',
    'overview.widget.rides_today': 'Fahrten heute',
    'overview.kiosk.chart_title': 'Umsatz',
    'overview.kiosk.chart_subtitle': 'Tägliche Einnahmen am Automaten',
    'overview.kiosk.chart_revenue': 'Umsatz',
    'overview.flow.title': 'Umsatzfluss',
    'overview.flow.subtitle': 'Online- und lokale Verkäufe der letzten 30 Tage zusammen',
    'overview.flow.payment_success': 'Zahlungserfolg',
    'overview.activity.title': 'Warnungen & Aktivität',
    'overview.activity.subtitle': 'Live-Warnungen, Support-Updates und aktuelle Betriebssignale',
    'overview.activity.none': 'Keine Warnungen oder Aktivitäten gefunden.',
    'overview.activity.cleared': 'Alle Warnungen wurden ausgeblendet.',
    'overview.activity.support': 'Support',
    'overview.activity.stripe': 'Stripe',
    'overview.activity.ops': 'Betrieb',
    'overview.activity.clear': 'Entfernen',
    'overview.recent_transactions': 'Letzte Transaktionen',
    'overview.recent_transactions.none': 'Keine aktuellen Transaktionen verfügbar.',
    'overview.recent_transactions.show_less': 'Weniger anzeigen',
    'overview.recent_transactions.show_all': 'Alle {count} anzeigen',
    'overview.kiosk.sale_title': 'Foto am Automaten verkauft',
    'overview.kiosk.sale_claimed': 'Später abgeholt: {email}',
    'overview.kiosk.sale_unknown': 'Kein Abholstatus bekannt',
    'overview.support_reply': 'Support-Antwort: {subject}',
    'overview.online_payment': 'Online-Zahlung',
    'overview.local_transaction': 'Lokale Transaktion',
    'overview.local_sale': '{method} Verkauf',
    'overview.stripe_payment_fallback': 'Stripe-Zahlung {id}',
    'revenue.subtitle_unified': 'Einheitliche Umsatzansicht für Online- und lokale Verkäufe',
    'revenue.partial_available': 'Umsatzdaten sind nur teilweise verfügbar.',
    'revenue.no_feed_title': 'Kein aktiver Umsatz-Feed',
    'revenue.no_feed_desc': 'Für diesen Park ist derzeit weder Stripe noch eine lokale Verkaufsquelle erreichbar. Die Seite füllt sich automatisch, sobald ein Feed verfügbar ist.',
    'revenue.kiosk.title': 'Selbstbedienungs-Automat',
    'revenue.kiosk.desc': 'Kein eigener Webshop hier — jedes gespeicherte Foto ist bereits ein bezahlter Kauf am Automaten ({price} pro Foto).',
    'revenue.kpi.today': 'Heute',
    'revenue.kpi.last_7_days': 'Letzte 7 Tage',
    'revenue.kpi.this_month': 'Dieser Monat',
    'revenue.kpi.total_since_records': 'Gesamt (seit Aufzeichnung)',
    'revenue.kpi.rides_today': 'Fahrten heute',
    'revenue.kpi.camera_captures_today': 'Kamera-Aufnahmen heute',
    'revenue.kpi.conversion_today': 'Conversion heute',
    'revenue.kpi.sold_per_ride': 'Verkauft je Fahrt',
    'revenue.kpi.total_revenue': 'Gesamtumsatz',
    'revenue.kpi.total_transactions': 'Gesamttransaktionen',
    'revenue.section.revenue': 'Umsatz',
    'revenue.section.daily_machine': 'Tägliche Einnahmen am Automaten',
    'revenue.section.hourly': 'Einnahmen nach Uhrzeit',
    'revenue.tab.total': 'Gesamt',
    'revenue.tab.today': 'Heute',
    'revenue.tab.yesterday': 'Gestern',
    'revenue.tab.other_day': 'Anderer Tag',
    'revenue.previous_day': 'Vorheriger Tag',
    'revenue.next_day': 'Nächster Tag',
    'revenue.select_day': 'Tag auswählen',
    'revenue.day_revenue': 'Am {date} eingenommen',
    'revenue.photos_sold': '{count} Fotos verkauft',
    'revenue.loading': 'Lädt...',
    'revenue.no_sales': 'Keine Verkäufe an diesem Tag.',
    'revenue.legend.revenue': 'Umsatz',
    'revenue.legend.rides': 'Fahrten',
    'revenue.daily_overview': 'Tagesübersicht',
    'revenue.no_sales_data': 'Noch keine Verkaufsdaten erfasst.',
    'revenue.table.day': 'Tag',
    'revenue.table.sold': 'Verkauft',
    'revenue.table.rides': 'Fahrten',
    'revenue.table.rate': 'Quote',
    'revenue.table.revenue': 'Umsatz',
    'revenue.online_commerce.title': 'Online-Commerce-Bereich',
    'revenue.online_commerce.subtitle': 'Stripe-Umsatz und Online-Käufe bleiben getrennt von der Automaten-Telemetrie.',
    'revenue.online_commerce.confirmed_revenue': 'Bestätigter Online-Umsatz: {value}',
    'revenue.online_commerce.successful_payments': 'Erfolgreiche Online-Zahlungen: {value}',
    'revenue.local_operations.title': 'Lokaler Betriebsbereich',
    'revenue.local_operations.subtitle': 'Nur bestätigte lokale Beträge zählen als Umsatz. Erkannte oder unbekannte Beträge bleiben außerhalb der Totale.',
    'revenue.local_operations.confirmed_revenue': 'Bestätigter lokaler Umsatz: {value}',
    'revenue.local_operations.detected_unconfirmed': 'Erkannt, aber unbestätigt: {value}',
    'revenue.local_operations.unknown_signals': 'Lokale Signale ohne Betrag: {value}',
    'revenue.trend.title': 'Umsatztrend',
    'revenue.trend.subtitle': 'Letzte 30 Tage, nur bestätigter Online- und lokaler Umsatz',
    'revenue.breakdown.title': 'Aufteilung lokaler Verkäufe',
    'revenue.breakdown.subtitle': 'Hier werden nur bestätigte lokale Bargeld- und Terminalbeträge dargestellt.',
    'revenue.signals.title': 'Verkaufssignale',
    'revenue.signals.payment_attempts': 'Zahlungsversuche',
    'revenue.signals.success_rate': 'Erfolgsquote',
    'revenue.signals.cancel_rate': 'Abbruchquote',
    'revenue.signals.cash_transactions': 'Bar- / Münztransaktionen',
    'revenue.signals.terminal_transactions': 'Terminaltransaktionen',
    'revenue.signals.unconfirmed_local_sales': 'Unbestätigte lokale Verkäufe',
    'revenue.signals.unknown_local_amounts': 'Unbekannte lokale Beträge',
    'revenue.legend.online': 'Online',
    'revenue.legend.local': 'Lokal',
    'revenue.cash': 'Bar',
    'revenue.terminal': 'Terminal',
    'revenue.detected_unconfirmed': 'Erkannt, unbestätigt: {value}',
    'revenue.local_display.detected': '{value} erkannt',
    'revenue.local_display.unknown': 'Unbekannt',
    'revenue.local_display.confirmed_only': 'Nur bestätigter lokaler Umsatz',
    'revenue.local_display.detected_only': 'In den Maschinendaten erkannt, aber nicht als Umsatz bestätigt',
    'revenue.local_display.unknown_only': 'Lokale Verkaufsaktivität ohne bestätigten Betrag',
    'revenue.local_display.none_yet': 'Noch kein bestätigter lokaler Umsatz',
    'purchases.subtitle_kiosk': 'Jedes Foto der letzten ~30 Tage, das am Automaten gekauft wurde',
    'purchases.subtitle_unified': 'Einheitliches Transaktionsprotokoll für Stripe- und Vor-Ort-Verkäufe',
    'purchases.partial_available': 'Transaktionsdaten sind nur teilweise verfügbar.',
    'purchases.table.source': 'Quelle',
    'purchases.table.customer_device': 'Kunde / Gerät',
    'purchases.table.payment': 'Zahlung',
    'purchases.table.description': 'Beschreibung',
    'purchases.source.online': 'Online',
    'purchases.source.local': 'Lokal',
    'purchases.source.kiosk': 'Automat',
    'purchases.source.automaton': 'Automat',
    'purchases.customer.stripe': 'Stripe-Kunde',
    'purchases.customer.local_device': 'Lokales Gerät',
    'purchases.customer.unknown': 'Unbekannt',
    'purchases.status.claimed': 'Abgeholt',
    'purchases.amount.detected': 'Erkannt, nicht bestätigt',
    'purchases.amount.none': 'Kein bestätigter Betrag',
    'purchases.filter.all': 'Alle Quellen',
    'purchases.filter.online': 'Nur online',
    'purchases.filter.local': 'Nur lokal',
    'purchases.description.kiosk_bought': 'Foto am Automaten gekauft',
    'purchases.description.kiosk_claimed': 'Foto am Automaten gekauft, später per QR-Code abgeholt ({email})',
    'photos.error_loading': 'Fehler beim Laden der Fotos',
    'photos.data_unavailable': 'Fotodaten sind derzeit nicht verfügbar.',
    'photos.for_day': 'Auswertung für {date}',
    'photos.for_day_desc': 'Kacheln und Kreise beziehen sich auf diesen Tag',
    'photos.previous_day': 'Vorheriger Tag',
    'photos.next_day': 'Nächster Tag',
    'photos.today': 'Heute',
    'photos.subtitle.day_captures': 'Aufnahmen · {date}',
    'photos.subtitle.sold_total': '{count} gesamt',
    'photos.subtitle.on_that_day': 'an diesem Tag',
    'photos.expired': 'Abgelaufen',
    'photos.conversion_chart': 'Conversion',
    'photos.not_purchased': 'Nicht gekauft',
    'photos.rides_without_purchase': 'Fahrten ohne Kauf',
    'photos.of_rides': 'von {count} Fahrten',
    'photos.by_attraction.none': 'Für diesen Tag liegen noch keine Attraktions-Daten vor.',
    'photos.by_attraction.captures': '{count} Aufnahmen',
    'photos.by_attraction.sold': '{count} verkauft',
    'photos.email_capture': 'E-Mail-Erfassung',
    'photos.email_capture.buyers': '{given} von {total} Käufern',
    'photos.email_capture.none': 'Keine Käufe an diesem Tag',
    'photos.browser.title': 'Foto-Browser',
    'photos.browser.refresh': 'Aktualisieren',
    'photos.browser.search_code': 'Bildnummer eingeben…',
    'photos.browser.search': 'Suchen',
    'photos.browser.reset': 'Suche zurücksetzen',
    'photos.browser.none': 'Keine Fotos gefunden.',
    'photos.browser.status.purchased': 'gekauft',
    'photos.browser.status.available': 'verfügbar',
    'photos.browser.photo_alt': 'Foto',
    'photos.browser.selected_alt': 'Ausgewähltes Foto',
    'photos.browser.copy_claim': 'Claim-Link kopieren',
    'photos.browser.copy_image': 'Bild-Link kopieren',
    'photos.browser.copied': 'Kopiert!',
    'photos.browser.claim_explainer': 'Claim-Link: der Kunde öffnet ihn und holt sein Foto per E-Mail (auch wenn der gedruckte QR falsch war). Bild-Link: direkter Download.',
    'photos.browser.select_prompt': 'Foto auswählen, um es hier groß anzuzeigen.',
  },
  en: {
    'kpi.vs_last_week': 'vs last week',
    'overview.last_data': 'Last data {time}',
    'overview.badge.stripe_enabled': 'Stripe enabled',
    'overview.badge.local_sales_active': 'Local sales active',
    'overview.badge.printer_telemetry': 'Printer telemetry',
    'overview.partial_data': 'Some data sources are currently unavailable.',
    'overview.kiosk.revenue_today': 'Revenue today',
    'overview.kiosk.photos_sold_today': 'Photos sold today',
    'overview.kiosk.photo_paper': 'Photo paper',
    'overview.kiosk.photos_sold_month': 'Photos sold (month)',
    'overview.kiosk.revenue_month': 'Revenue (month)',
    'overview.kiosk.photos_sold_total': 'Photos sold (total)',
    'overview.online_revenue': 'Online Revenue',
    'overview.local_revenue': 'Local Revenue',
    'overview.transactions': 'Transactions',
    'overview.errors': 'Errors',
    'overview.warnings': 'Warnings',
    'overview.paper_remaining': 'Paper Remaining',
    'overview.print_count': 'Print Count',
    'overview.widget.last_activity': 'Last activity',
    'overview.widget.open_system_health': 'Open system health',
    'overview.widget.data_files_scanned': 'Data files scanned',
    'overview.widget.recognized_ops_files': 'Recognized ops files',
    'overview.widget.open_operations': 'Open operations',
    'overview.widget.users': 'Users',
    'overview.widget.open_users': 'Open users',
    'overview.widget.photos': 'Photos',
    'overview.widget.open_photos': 'Open photos',
    'overview.widget.active_attractions': 'Active attractions',
    'overview.widget.conversion_today': 'Conversion today',
    'overview.widget.sold_per_ride': 'Sold per ride',
    'overview.widget.rides_today': 'Rides today',
    'overview.kiosk.chart_title': 'Revenue',
    'overview.kiosk.chart_subtitle': 'Daily kiosk revenue',
    'overview.kiosk.chart_revenue': 'Revenue',
    'overview.flow.title': 'Revenue Flow',
    'overview.flow.subtitle': 'Online and local sales combined over the last 30 days',
    'overview.flow.payment_success': 'Payment Success',
    'overview.activity.title': 'Alerts & Activity',
    'overview.activity.subtitle': 'Live warnings, support updates and recent operational signals',
    'overview.activity.none': 'No alerts or activity found.',
    'overview.activity.cleared': 'All alerts have been cleared.',
    'overview.activity.support': 'Support',
    'overview.activity.stripe': 'Stripe',
    'overview.activity.ops': 'Ops',
    'overview.activity.clear': 'Clear',
    'overview.recent_transactions': 'Recent Transactions',
    'overview.recent_transactions.none': 'No recent transactions available.',
    'overview.recent_transactions.show_less': 'Show less',
    'overview.recent_transactions.show_all': 'Show all {count}',
    'overview.kiosk.sale_title': 'Photo sold at kiosk',
    'overview.kiosk.sale_claimed': 'Claimed later: {email}',
    'overview.kiosk.sale_unknown': 'No claim status known',
    'overview.support_reply': 'Support reply: {subject}',
    'overview.online_payment': 'Online payment',
    'overview.local_transaction': 'Local transaction',
    'overview.local_sale': '{method} sale',
    'overview.stripe_payment_fallback': 'Stripe payment {id}',
    'revenue.subtitle_unified': 'Unified revenue view for online and local sales',
    'revenue.partial_available': 'Revenue is partially available.',
    'revenue.no_feed_title': 'No active revenue feed',
    'revenue.no_feed_desc': 'This park currently has no reachable Stripe or local sales source. The page will populate automatically as soon as one of the feeds is available.',
    'revenue.kiosk.title': 'Self-service kiosk',
    'revenue.kiosk.desc': 'There is no separate webshop here — every stored photo is already a paid kiosk purchase ({price} per photo).',
    'revenue.kpi.today': 'Today',
    'revenue.kpi.last_7_days': 'Last 7 days',
    'revenue.kpi.this_month': 'This month',
    'revenue.kpi.total_since_records': 'Total (since recording started)',
    'revenue.kpi.rides_today': 'Rides today',
    'revenue.kpi.camera_captures_today': 'Camera captures today',
    'revenue.kpi.conversion_today': 'Conversion today',
    'revenue.kpi.sold_per_ride': 'Sold per ride',
    'revenue.kpi.total_revenue': 'Total Revenue',
    'revenue.kpi.total_transactions': 'Total Transactions',
    'revenue.section.revenue': 'Revenue',
    'revenue.section.daily_machine': 'Daily kiosk revenue',
    'revenue.section.hourly': 'Revenue by hour',
    'revenue.tab.total': 'Total',
    'revenue.tab.today': 'Today',
    'revenue.tab.yesterday': 'Yesterday',
    'revenue.tab.other_day': 'Other day',
    'revenue.previous_day': 'Previous day',
    'revenue.next_day': 'Next day',
    'revenue.select_day': 'Select day',
    'revenue.day_revenue': 'Revenue on {date}',
    'revenue.photos_sold': '{count} photos sold',
    'revenue.loading': 'Loading...',
    'revenue.no_sales': 'No sales on this day.',
    'revenue.legend.revenue': 'Revenue',
    'revenue.legend.rides': 'Rides',
    'revenue.daily_overview': 'Daily overview',
    'revenue.no_sales_data': 'No sales data recorded yet.',
    'revenue.table.day': 'Day',
    'revenue.table.sold': 'Sold',
    'revenue.table.rides': 'Rides',
    'revenue.table.rate': 'Rate',
    'revenue.table.revenue': 'Revenue',
    'revenue.online_commerce.title': 'Online commerce domain',
    'revenue.online_commerce.subtitle': 'Stripe revenue and online purchase counts stay separate from machine-side telemetry.',
    'revenue.online_commerce.confirmed_revenue': 'Confirmed online revenue: {value}',
    'revenue.online_commerce.successful_payments': 'Online successful payments: {value}',
    'revenue.local_operations.title': 'Local operations domain',
    'revenue.local_operations.subtitle': 'Only confirmed local amounts count as revenue. Detected or unknown amounts stay outside totals.',
    'revenue.local_operations.confirmed_revenue': 'Confirmed local revenue: {value}',
    'revenue.local_operations.detected_unconfirmed': 'Detected but unconfirmed local amount: {value}',
    'revenue.local_operations.unknown_signals': 'Unknown local amount signals: {value}',
    'revenue.trend.title': 'Revenue Trend',
    'revenue.trend.subtitle': 'Last 30 days, confirmed online and confirmed local revenue only',
    'revenue.breakdown.title': 'Local Sales Breakdown',
    'revenue.breakdown.subtitle': 'Only confirmed local cash and terminal amounts are charted here.',
    'revenue.signals.title': 'Sales Signals',
    'revenue.signals.payment_attempts': 'Payment attempts',
    'revenue.signals.success_rate': 'Success rate',
    'revenue.signals.cancel_rate': 'Cancel rate',
    'revenue.signals.cash_transactions': 'Cash / coin transactions',
    'revenue.signals.terminal_transactions': 'Terminal transactions',
    'revenue.signals.unconfirmed_local_sales': 'Unconfirmed local sales',
    'revenue.signals.unknown_local_amounts': 'Unknown local amounts',
    'revenue.legend.online': 'Online',
    'revenue.legend.local': 'Local',
    'revenue.cash': 'Cash',
    'revenue.terminal': 'Terminal',
    'revenue.detected_unconfirmed': 'Detected, unconfirmed: {value}',
    'revenue.local_display.detected': '{value} detected',
    'revenue.local_display.unknown': 'Unknown',
    'revenue.local_display.confirmed_only': 'Confirmed local revenue only',
    'revenue.local_display.detected_only': 'Detected in machine data, not confirmed as revenue',
    'revenue.local_display.unknown_only': 'Local sales activity exists without a confirmed amount',
    'revenue.local_display.none_yet': 'No confirmed local revenue yet',
    'purchases.subtitle_kiosk': 'Every photo from the last ~30 days that was purchased at the kiosk',
    'purchases.subtitle_unified': 'Unified transaction log for Stripe and on-site sales',
    'purchases.partial_available': 'Transaction data is partially available.',
    'purchases.table.source': 'Source',
    'purchases.table.customer_device': 'Customer / Device',
    'purchases.table.payment': 'Payment',
    'purchases.table.description': 'Description',
    'purchases.source.online': 'Online',
    'purchases.source.local': 'Local',
    'purchases.source.kiosk': 'Kiosk',
    'purchases.source.automaton': 'Kiosk',
    'purchases.customer.stripe': 'Stripe customer',
    'purchases.customer.local_device': 'Local device',
    'purchases.customer.unknown': 'Unknown',
    'purchases.status.claimed': 'Claimed',
    'purchases.amount.detected': 'Detected, not confirmed',
    'purchases.amount.none': 'No confirmed amount',
    'purchases.filter.all': 'All sources',
    'purchases.filter.online': 'Online only',
    'purchases.filter.local': 'Local only',
    'purchases.description.kiosk_bought': 'Photo purchased at kiosk',
    'purchases.description.kiosk_claimed': 'Photo purchased at kiosk, claimed later via QR code ({email})',
    'photos.error_loading': 'Error Loading Photos',
    'photos.data_unavailable': 'Photo data is currently unavailable.',
    'photos.for_day': 'Analysis for {date}',
    'photos.for_day_desc': 'Tiles and circles refer to this day',
    'photos.previous_day': 'Previous day',
    'photos.next_day': 'Next day',
    'photos.today': 'Today',
    'photos.subtitle.day_captures': 'Captures · {date}',
    'photos.subtitle.sold_total': '{count} total',
    'photos.subtitle.on_that_day': 'on that day',
    'photos.expired': 'Expired',
    'photos.conversion_chart': 'Conversion',
    'photos.not_purchased': 'Not purchased',
    'photos.rides_without_purchase': 'Rides without purchase',
    'photos.of_rides': 'out of {count} rides',
    'photos.by_attraction.none': 'No attraction data is available for this day yet.',
    'photos.by_attraction.captures': '{count} captures',
    'photos.by_attraction.sold': '{count} sold',
    'photos.email_capture': 'Email capture',
    'photos.email_capture.buyers': '{given} of {total} buyers',
    'photos.email_capture.none': 'No purchases on this day',
    'photos.browser.title': 'Photo Browser',
    'photos.browser.refresh': 'Refresh',
    'photos.browser.search_code': 'Enter photo number…',
    'photos.browser.search': 'Search',
    'photos.browser.reset': 'Reset search',
    'photos.browser.none': 'No photos found.',
    'photos.browser.status.purchased': 'purchased',
    'photos.browser.status.available': 'available',
    'photos.browser.photo_alt': 'Photo',
    'photos.browser.selected_alt': 'Selected photo',
    'photos.browser.copy_claim': 'Copy claim link',
    'photos.browser.copy_image': 'Copy image link',
    'photos.browser.copied': 'Copied!',
    'photos.browser.claim_explainer': 'Claim link: the customer opens it and retrieves the photo by email (even if the printed QR was wrong). Image link: direct download.',
    'photos.browser.select_prompt': 'Select a photo to display it large here.',
  },
  es: {
    'kpi.vs_last_week': 'vs la semana pasada',
    'overview.last_data': 'Últimos datos {time}',
    'overview.badge.stripe_enabled': 'Stripe activo',
    'overview.badge.local_sales_active': 'Ventas locales activas',
    'overview.badge.printer_telemetry': 'Telemetría de impresora',
    'overview.partial_data': 'Algunas fuentes de datos no están disponibles en este momento.',
    'overview.kiosk.revenue_today': 'Ingresos de hoy',
    'overview.kiosk.photos_sold_today': 'Fotos vendidas hoy',
    'overview.kiosk.photo_paper': 'Papel fotográfico',
    'overview.kiosk.photos_sold_month': 'Fotos vendidas (mes)',
    'overview.kiosk.revenue_month': 'Ingresos (mes)',
    'overview.kiosk.photos_sold_total': 'Fotos vendidas (total)',
    'overview.online_revenue': 'Ingresos online',
    'overview.local_revenue': 'Ingresos locales',
    'overview.transactions': 'Transacciones',
    'overview.errors': 'Errores',
    'overview.warnings': 'Advertencias',
    'overview.paper_remaining': 'Papel restante',
    'overview.print_count': 'Número de impresiones',
    'overview.widget.last_activity': 'Última actividad',
    'overview.widget.open_system_health': 'Abrir estado del sistema',
    'overview.widget.data_files_scanned': 'Archivos de datos escaneados',
    'overview.widget.recognized_ops_files': 'Archivos operativos reconocidos',
    'overview.widget.open_operations': 'Abrir operaciones',
    'overview.widget.users': 'Usuarios',
    'overview.widget.open_users': 'Abrir usuarios',
    'overview.widget.photos': 'Fotos',
    'overview.widget.open_photos': 'Abrir fotos',
    'overview.widget.active_attractions': 'Atracciones activas',
    'overview.widget.conversion_today': 'Conversión de hoy',
    'overview.widget.sold_per_ride': 'Vendidas por viaje',
    'overview.widget.rides_today': 'Viajes de hoy',
    'overview.kiosk.chart_title': 'Ingresos',
    'overview.kiosk.chart_subtitle': 'Ingresos diarios del quiosco',
    'overview.kiosk.chart_revenue': 'Ingresos',
    'overview.flow.title': 'Flujo de ingresos',
    'overview.flow.subtitle': 'Ventas online y locales combinadas durante los últimos 30 días',
    'overview.flow.payment_success': 'Pagos correctos',
    'overview.activity.title': 'Alertas y actividad',
    'overview.activity.subtitle': 'Alertas en vivo, respuestas de soporte y señales operativas recientes',
    'overview.activity.none': 'No se encontraron alertas ni actividad.',
    'overview.activity.cleared': 'Todas las alertas se han ocultado.',
    'overview.activity.support': 'Soporte',
    'overview.activity.stripe': 'Stripe',
    'overview.activity.ops': 'Operaciones',
    'overview.activity.clear': 'Quitar',
    'overview.recent_transactions': 'Transacciones recientes',
    'overview.recent_transactions.none': 'No hay transacciones recientes disponibles.',
    'overview.recent_transactions.show_less': 'Mostrar menos',
    'overview.recent_transactions.show_all': 'Mostrar las {count}',
    'overview.kiosk.sale_title': 'Foto vendida en el quiosco',
    'overview.kiosk.sale_claimed': 'Recogida más tarde: {email}',
    'overview.kiosk.sale_unknown': 'Sin estado de recogida',
    'overview.support_reply': 'Respuesta de soporte: {subject}',
    'overview.online_payment': 'Pago online',
    'overview.local_transaction': 'Transacción local',
    'overview.local_sale': 'Venta {method}',
    'overview.stripe_payment_fallback': 'Pago Stripe {id}',
    'revenue.subtitle_unified': 'Vista unificada de ingresos para ventas online y locales',
    'revenue.partial_available': 'Los ingresos están disponibles solo parcialmente.',
    'revenue.no_feed_title': 'No hay feed de ingresos activo',
    'revenue.no_feed_desc': 'Este parque no tiene actualmente una fuente de Stripe o ventas locales disponible. La página se llenará automáticamente en cuanto haya una fuente accesible.',
    'revenue.kiosk.title': 'Quiosco de autoservicio',
    'revenue.kiosk.desc': 'Aquí no hay una tienda online separada: cada foto guardada ya es una compra pagada en el quiosco ({price} por foto).',
    'revenue.kpi.today': 'Hoy',
    'revenue.kpi.last_7_days': 'Últimos 7 días',
    'revenue.kpi.this_month': 'Este mes',
    'revenue.kpi.total_since_records': 'Total (desde el inicio del registro)',
    'revenue.kpi.rides_today': 'Viajes hoy',
    'revenue.kpi.camera_captures_today': 'Capturas de cámara hoy',
    'revenue.kpi.conversion_today': 'Conversión hoy',
    'revenue.kpi.sold_per_ride': 'Vendidas por viaje',
    'revenue.kpi.total_revenue': 'Ingresos totales',
    'revenue.kpi.total_transactions': 'Transacciones totales',
    'revenue.section.revenue': 'Ingresos',
    'revenue.section.daily_machine': 'Ingresos diarios del quiosco',
    'revenue.section.hourly': 'Ingresos por hora',
    'revenue.tab.total': 'Total',
    'revenue.tab.today': 'Hoy',
    'revenue.tab.yesterday': 'Ayer',
    'revenue.tab.other_day': 'Otro día',
    'revenue.previous_day': 'Día anterior',
    'revenue.next_day': 'Día siguiente',
    'revenue.select_day': 'Seleccionar día',
    'revenue.day_revenue': 'Ingresos el {date}',
    'revenue.photos_sold': '{count} fotos vendidas',
    'revenue.loading': 'Cargando...',
    'revenue.no_sales': 'No hubo ventas ese día.',
    'revenue.legend.revenue': 'Ingresos',
    'revenue.legend.rides': 'Viajes',
    'revenue.daily_overview': 'Resumen diario',
    'revenue.no_sales_data': 'Aún no hay datos de ventas.',
    'revenue.table.day': 'Día',
    'revenue.table.sold': 'Vendidas',
    'revenue.table.rides': 'Viajes',
    'revenue.table.rate': 'Tasa',
    'revenue.table.revenue': 'Ingresos',
    'revenue.online_commerce.title': 'Área de comercio online',
    'revenue.online_commerce.subtitle': 'Los ingresos de Stripe y los recuentos de compras online se mantienen separados de la telemetría de la máquina.',
    'revenue.online_commerce.confirmed_revenue': 'Ingresos online confirmados: {value}',
    'revenue.online_commerce.successful_payments': 'Pagos online exitosos: {value}',
    'revenue.local_operations.title': 'Área operativa local',
    'revenue.local_operations.subtitle': 'Solo los importes locales confirmados cuentan como ingresos. Los importes detectados o desconocidos quedan fuera de los totales.',
    'revenue.local_operations.confirmed_revenue': 'Ingresos locales confirmados: {value}',
    'revenue.local_operations.detected_unconfirmed': 'Importe local detectado pero no confirmado: {value}',
    'revenue.local_operations.unknown_signals': 'Señales locales sin importe: {value}',
    'revenue.trend.title': 'Tendencia de ingresos',
    'revenue.trend.subtitle': 'Últimos 30 días, solo ingresos confirmados online y locales',
    'revenue.breakdown.title': 'Desglose de ventas locales',
    'revenue.breakdown.subtitle': 'Aquí solo se muestran importes locales confirmados en efectivo y terminal.',
    'revenue.signals.title': 'Señales de venta',
    'revenue.signals.payment_attempts': 'Intentos de pago',
    'revenue.signals.success_rate': 'Tasa de éxito',
    'revenue.signals.cancel_rate': 'Tasa de cancelación',
    'revenue.signals.cash_transactions': 'Transacciones en efectivo / monedas',
    'revenue.signals.terminal_transactions': 'Transacciones de terminal',
    'revenue.signals.unconfirmed_local_sales': 'Ventas locales no confirmadas',
    'revenue.signals.unknown_local_amounts': 'Importes locales desconocidos',
    'revenue.legend.online': 'Online',
    'revenue.legend.local': 'Local',
    'revenue.cash': 'Efectivo',
    'revenue.terminal': 'Terminal',
    'revenue.detected_unconfirmed': 'Detectado, no confirmado: {value}',
    'revenue.local_display.detected': '{value} detectado',
    'revenue.local_display.unknown': 'Desconocido',
    'revenue.local_display.confirmed_only': 'Solo ingresos locales confirmados',
    'revenue.local_display.detected_only': 'Detectado en la máquina, pero no confirmado como ingreso',
    'revenue.local_display.unknown_only': 'Hay actividad de ventas locales sin importe confirmado',
    'revenue.local_display.none_yet': 'Aún no hay ingresos locales confirmados',
    'purchases.subtitle_kiosk': 'Cada foto de los últimos ~30 días que se compró en el quiosco',
    'purchases.subtitle_unified': 'Registro unificado de transacciones para Stripe y ventas presenciales',
    'purchases.partial_available': 'Los datos de transacciones están disponibles solo parcialmente.',
    'purchases.table.source': 'Fuente',
    'purchases.table.customer_device': 'Cliente / Dispositivo',
    'purchases.table.payment': 'Pago',
    'purchases.table.description': 'Descripción',
    'purchases.source.online': 'Online',
    'purchases.source.local': 'Local',
    'purchases.source.kiosk': 'Quiosco',
    'purchases.source.automaton': 'Quiosco',
    'purchases.customer.stripe': 'Cliente de Stripe',
    'purchases.customer.local_device': 'Dispositivo local',
    'purchases.customer.unknown': 'Desconocido',
    'purchases.status.claimed': 'Recogido',
    'purchases.amount.detected': 'Detectado, no confirmado',
    'purchases.amount.none': 'Sin importe confirmado',
    'purchases.filter.all': 'Todas las fuentes',
    'purchases.filter.online': 'Solo online',
    'purchases.filter.local': 'Solo local',
    'purchases.description.kiosk_bought': 'Foto comprada en el quiosco',
    'purchases.description.kiosk_claimed': 'Foto comprada en el quiosco y recogida más tarde por QR ({email})',
    'photos.error_loading': 'Error al cargar las fotos',
    'photos.data_unavailable': 'Los datos de fotos no están disponibles actualmente.',
    'photos.for_day': 'Análisis para {date}',
    'photos.for_day_desc': 'Las tarjetas y los círculos se refieren a este día',
    'photos.previous_day': 'Día anterior',
    'photos.next_day': 'Día siguiente',
    'photos.today': 'Hoy',
    'photos.subtitle.day_captures': 'Capturas · {date}',
    'photos.subtitle.sold_total': '{count} total',
    'photos.subtitle.on_that_day': 'ese día',
    'photos.expired': 'Caducadas',
    'photos.conversion_chart': 'Conversión',
    'photos.not_purchased': 'No compradas',
    'photos.rides_without_purchase': 'Viajes sin compra',
    'photos.of_rides': 'de {count} viajes',
    'photos.by_attraction.none': 'Aún no hay datos de atracciones para este día.',
    'photos.by_attraction.captures': '{count} capturas',
    'photos.by_attraction.sold': '{count} vendidas',
    'photos.email_capture': 'Captura de e-mail',
    'photos.email_capture.buyers': '{given} de {total} compradores',
    'photos.email_capture.none': 'No hubo compras ese día',
    'photos.browser.title': 'Navegador de fotos',
    'photos.browser.refresh': 'Actualizar',
    'photos.browser.search_code': 'Introducir número de foto…',
    'photos.browser.search': 'Buscar',
    'photos.browser.reset': 'Restablecer búsqueda',
    'photos.browser.none': 'No se encontraron fotos.',
    'photos.browser.status.purchased': 'comprada',
    'photos.browser.status.available': 'disponible',
    'photos.browser.photo_alt': 'Foto',
    'photos.browser.selected_alt': 'Foto seleccionada',
    'photos.browser.copy_claim': 'Copiar enlace de claim',
    'photos.browser.copy_image': 'Copiar enlace de imagen',
    'photos.browser.copied': '¡Copiado!',
    'photos.browser.claim_explainer': 'Enlace de claim: el cliente lo abre y recupera su foto por e-mail (aunque el QR impreso fuera incorrecto). Enlace de imagen: descarga directa.',
    'photos.browser.select_prompt': 'Selecciona una foto para verla grande aquí.',
  },
  fr: {
    'kpi.vs_last_week': 'vs semaine dernière',
    'overview.last_data': 'Dernières données {time}',
    'overview.badge.stripe_enabled': 'Stripe actif',
    'overview.badge.local_sales_active': 'Ventes locales actives',
    'overview.badge.printer_telemetry': 'Télémétrie imprimante',
    'overview.partial_data': 'Certaines sources de données sont actuellement indisponibles.',
    'overview.kiosk.revenue_today': 'Revenus du jour',
    'overview.kiosk.photos_sold_today': 'Photos vendues aujourd’hui',
    'overview.kiosk.photo_paper': 'Papier photo',
    'overview.kiosk.photos_sold_month': 'Photos vendues (mois)',
    'overview.kiosk.revenue_month': 'Revenus (mois)',
    'overview.kiosk.photos_sold_total': 'Photos vendues (total)',
    'overview.online_revenue': 'Revenus en ligne',
    'overview.local_revenue': 'Revenus locaux',
    'overview.transactions': 'Transactions',
    'overview.errors': 'Erreurs',
    'overview.warnings': 'Avertissements',
    'overview.paper_remaining': 'Papier restant',
    'overview.print_count': 'Nombre d’impressions',
    'overview.widget.last_activity': 'Dernière activité',
    'overview.widget.open_system_health': 'Ouvrir la santé système',
    'overview.widget.data_files_scanned': 'Fichiers de données scannés',
    'overview.widget.recognized_ops_files': 'Fichiers opérationnels reconnus',
    'overview.widget.open_operations': 'Ouvrir les opérations',
    'overview.widget.users': 'Utilisateurs',
    'overview.widget.open_users': 'Ouvrir les utilisateurs',
    'overview.widget.photos': 'Photos',
    'overview.widget.open_photos': 'Ouvrir les photos',
    'overview.widget.active_attractions': 'Attractions actives',
    'overview.widget.conversion_today': 'Conversion du jour',
    'overview.widget.sold_per_ride': 'Vendues par passage',
    'overview.widget.rides_today': 'Passages du jour',
    'overview.kiosk.chart_title': 'Revenus',
    'overview.kiosk.chart_subtitle': 'Revenus quotidiens de la borne',
    'overview.kiosk.chart_revenue': 'Revenus',
    'overview.flow.title': 'Flux de revenus',
    'overview.flow.subtitle': 'Ventes en ligne et locales combinées sur les 30 derniers jours',
    'overview.flow.payment_success': 'Paiements réussis',
    'overview.activity.title': 'Alertes & activité',
    'overview.activity.subtitle': 'Alertes en direct, réponses support et signaux opérationnels récents',
    'overview.activity.none': 'Aucune alerte ni activité.',
    'overview.activity.cleared': 'Toutes les alertes ont été masquées.',
    'overview.activity.support': 'Support',
    'overview.activity.stripe': 'Stripe',
    'overview.activity.ops': 'Ops',
    'overview.activity.clear': 'Effacer',
    'overview.recent_transactions': 'Transactions récentes',
    'overview.recent_transactions.none': 'Aucune transaction récente disponible.',
    'overview.recent_transactions.show_less': 'Afficher moins',
    'overview.recent_transactions.show_all': 'Afficher les {count}',
    'overview.kiosk.sale_title': 'Photo vendue à la borne',
    'overview.kiosk.sale_claimed': 'Récupérée plus tard : {email}',
    'overview.kiosk.sale_unknown': 'Aucun statut de récupération',
    'overview.support_reply': 'Réponse support : {subject}',
    'overview.online_payment': 'Paiement en ligne',
    'overview.local_transaction': 'Transaction locale',
    'overview.local_sale': 'Vente {method}',
    'overview.stripe_payment_fallback': 'Paiement Stripe {id}',
    'revenue.subtitle_unified': 'Vue unifiée des revenus en ligne et locaux',
    'revenue.partial_available': 'Les revenus sont partiellement disponibles.',
    'revenue.no_feed_title': 'Aucun flux de revenus actif',
    'revenue.no_feed_desc': 'Ce parc n’a actuellement aucune source Stripe ou vente locale accessible. La page se remplira automatiquement dès qu’une source sera disponible.',
    'revenue.kiosk.title': 'Borne en libre-service',
    'revenue.kiosk.desc': 'Il n’y a pas de boutique en ligne séparée ici — chaque photo enregistrée est déjà un achat payé à la borne ({price} par photo).',
    'revenue.kpi.today': 'Aujourd’hui',
    'revenue.kpi.last_7_days': '7 derniers jours',
    'revenue.kpi.this_month': 'Ce mois-ci',
    'revenue.kpi.total_since_records': 'Total (depuis le début)',
    'revenue.kpi.rides_today': 'Passages aujourd’hui',
    'revenue.kpi.camera_captures_today': 'Captures caméra du jour',
    'revenue.kpi.conversion_today': 'Conversion du jour',
    'revenue.kpi.sold_per_ride': 'Vendues par passage',
    'revenue.kpi.total_revenue': 'Revenu total',
    'revenue.kpi.total_transactions': 'Transactions totales',
    'revenue.section.revenue': 'Revenus',
    'revenue.section.daily_machine': 'Revenus quotidiens de la borne',
    'revenue.section.hourly': 'Revenus par heure',
    'revenue.tab.total': 'Total',
    'revenue.tab.today': 'Aujourd’hui',
    'revenue.tab.yesterday': 'Hier',
    'revenue.tab.other_day': 'Autre jour',
    'revenue.previous_day': 'Jour précédent',
    'revenue.next_day': 'Jour suivant',
    'revenue.select_day': 'Choisir un jour',
    'revenue.day_revenue': 'Revenus le {date}',
    'revenue.photos_sold': '{count} photos vendues',
    'revenue.loading': 'Chargement...',
    'revenue.no_sales': 'Aucune vente ce jour-là.',
    'revenue.legend.revenue': 'Revenus',
    'revenue.legend.rides': 'Passages',
    'revenue.daily_overview': 'Vue journalière',
    'revenue.no_sales_data': 'Aucune donnée de vente enregistrée pour le moment.',
    'revenue.table.day': 'Jour',
    'revenue.table.sold': 'Vendues',
    'revenue.table.rides': 'Passages',
    'revenue.table.rate': 'Taux',
    'revenue.table.revenue': 'Revenus',
    'revenue.online_commerce.title': 'Domaine commerce en ligne',
    'revenue.online_commerce.subtitle': 'Les revenus Stripe et les achats en ligne restent séparés de la télémétrie machine.',
    'revenue.online_commerce.confirmed_revenue': 'Revenus en ligne confirmés : {value}',
    'revenue.online_commerce.successful_payments': 'Paiements en ligne réussis : {value}',
    'revenue.local_operations.title': 'Domaine opérations locales',
    'revenue.local_operations.subtitle': 'Seuls les montants locaux confirmés comptent comme revenus. Les montants détectés ou inconnus restent hors des totaux.',
    'revenue.local_operations.confirmed_revenue': 'Revenus locaux confirmés : {value}',
    'revenue.local_operations.detected_unconfirmed': 'Montant local détecté mais non confirmé : {value}',
    'revenue.local_operations.unknown_signals': 'Signaux locaux sans montant : {value}',
    'revenue.trend.title': 'Tendance des revenus',
    'revenue.trend.subtitle': '30 derniers jours, uniquement revenus en ligne et locaux confirmés',
    'revenue.breakdown.title': 'Répartition des ventes locales',
    'revenue.breakdown.subtitle': 'Seuls les montants locaux confirmés en espèces et au terminal sont affichés ici.',
    'revenue.signals.title': 'Signaux de vente',
    'revenue.signals.payment_attempts': 'Tentatives de paiement',
    'revenue.signals.success_rate': 'Taux de réussite',
    'revenue.signals.cancel_rate': 'Taux d’annulation',
    'revenue.signals.cash_transactions': 'Transactions espèces / pièces',
    'revenue.signals.terminal_transactions': 'Transactions terminal',
    'revenue.signals.unconfirmed_local_sales': 'Ventes locales non confirmées',
    'revenue.signals.unknown_local_amounts': 'Montants locaux inconnus',
    'revenue.legend.online': 'En ligne',
    'revenue.legend.local': 'Local',
    'revenue.cash': 'Espèces',
    'revenue.terminal': 'Terminal',
    'revenue.detected_unconfirmed': 'Détecté, non confirmé : {value}',
    'revenue.local_display.detected': '{value} détecté',
    'revenue.local_display.unknown': 'Inconnu',
    'revenue.local_display.confirmed_only': 'Revenus locaux confirmés uniquement',
    'revenue.local_display.detected_only': 'Détecté dans la machine, mais non confirmé comme revenu',
    'revenue.local_display.unknown_only': 'Une activité locale existe sans montant confirmé',
    'revenue.local_display.none_yet': 'Pas encore de revenus locaux confirmés',
    'purchases.subtitle_kiosk': 'Chaque photo des ~30 derniers jours achetée à la borne',
    'purchases.subtitle_unified': 'Journal unifié des transactions Stripe et sur site',
    'purchases.partial_available': 'Les données de transaction sont partiellement disponibles.',
    'purchases.table.source': 'Source',
    'purchases.table.customer_device': 'Client / Appareil',
    'purchases.table.payment': 'Paiement',
    'purchases.table.description': 'Description',
    'purchases.source.online': 'En ligne',
    'purchases.source.local': 'Local',
    'purchases.source.kiosk': 'Borne',
    'purchases.source.automaton': 'Borne',
    'purchases.customer.stripe': 'Client Stripe',
    'purchases.customer.local_device': 'Appareil local',
    'purchases.customer.unknown': 'Inconnu',
    'purchases.status.claimed': 'Récupérée',
    'purchases.amount.detected': 'Détecté, non confirmé',
    'purchases.amount.none': 'Aucun montant confirmé',
    'purchases.filter.all': 'Toutes les sources',
    'purchases.filter.online': 'En ligne uniquement',
    'purchases.filter.local': 'Local uniquement',
    'purchases.description.kiosk_bought': 'Photo achetée à la borne',
    'purchases.description.kiosk_claimed': 'Photo achetée à la borne puis récupérée via QR ({email})',
    'photos.error_loading': 'Erreur de chargement des photos',
    'photos.data_unavailable': 'Les données photo sont actuellement indisponibles.',
    'photos.for_day': 'Analyse pour {date}',
    'photos.for_day_desc': 'Les tuiles et les cercles se rapportent à ce jour',
    'photos.previous_day': 'Jour précédent',
    'photos.next_day': 'Jour suivant',
    'photos.today': 'Aujourd’hui',
    'photos.subtitle.day_captures': 'Captures · {date}',
    'photos.subtitle.sold_total': '{count} au total',
    'photos.subtitle.on_that_day': 'ce jour-là',
    'photos.expired': 'Expirées',
    'photos.conversion_chart': 'Conversion',
    'photos.not_purchased': 'Non achetées',
    'photos.rides_without_purchase': 'Passages sans achat',
    'photos.of_rides': 'sur {count} passages',
    'photos.by_attraction.none': 'Aucune donnée d’attraction pour ce jour pour le moment.',
    'photos.by_attraction.captures': '{count} captures',
    'photos.by_attraction.sold': '{count} vendues',
    'photos.email_capture': 'Collecte e-mail',
    'photos.email_capture.buyers': '{given} sur {total} acheteurs',
    'photos.email_capture.none': 'Aucun achat ce jour-là',
    'photos.browser.title': 'Navigateur photo',
    'photos.browser.refresh': 'Actualiser',
    'photos.browser.search_code': 'Saisir le numéro photo…',
    'photos.browser.search': 'Rechercher',
    'photos.browser.reset': 'Réinitialiser la recherche',
    'photos.browser.none': 'Aucune photo trouvée.',
    'photos.browser.status.purchased': 'achetée',
    'photos.browser.status.available': 'disponible',
    'photos.browser.photo_alt': 'Photo',
    'photos.browser.selected_alt': 'Photo sélectionnée',
    'photos.browser.copy_claim': 'Copier le lien de claim',
    'photos.browser.copy_image': 'Copier le lien image',
    'photos.browser.copied': 'Copié !',
    'photos.browser.claim_explainer': 'Lien de claim : le client l’ouvre et récupère sa photo par e-mail (même si le QR imprimé était faux). Lien image : téléchargement direct.',
    'photos.browser.select_prompt': 'Sélectionne une photo pour l’afficher en grand ici.',
  },
  it: {
    'kpi.vs_last_week': 'vs settimana scorsa',
    'overview.last_data': 'Ultimi dati {time}',
    'overview.badge.stripe_enabled': 'Stripe attivo',
    'overview.badge.local_sales_active': 'Vendite locali attive',
    'overview.badge.printer_telemetry': 'Telemetria stampante',
    'overview.partial_data': 'Alcune fonti dati non sono attualmente disponibili.',
    'overview.kiosk.revenue_today': 'Ricavi di oggi',
    'overview.kiosk.photos_sold_today': 'Foto vendute oggi',
    'overview.kiosk.photo_paper': 'Carta fotografica',
    'overview.kiosk.photos_sold_month': 'Foto vendute (mese)',
    'overview.kiosk.revenue_month': 'Ricavi (mese)',
    'overview.kiosk.photos_sold_total': 'Foto vendute (totale)',
    'overview.online_revenue': 'Ricavi online',
    'overview.local_revenue': 'Ricavi locali',
    'overview.transactions': 'Transazioni',
    'overview.errors': 'Errori',
    'overview.warnings': 'Avvisi',
    'overview.paper_remaining': 'Carta rimanente',
    'overview.print_count': 'Numero stampe',
    'overview.widget.last_activity': 'Ultima attività',
    'overview.widget.open_system_health': 'Apri stato sistema',
    'overview.widget.data_files_scanned': 'File dati scansionati',
    'overview.widget.recognized_ops_files': 'File operativi riconosciuti',
    'overview.widget.open_operations': 'Apri operazioni',
    'overview.widget.users': 'Utenti',
    'overview.widget.open_users': 'Apri utenti',
    'overview.widget.photos': 'Foto',
    'overview.widget.open_photos': 'Apri foto',
    'overview.widget.active_attractions': 'Attrazioni attive',
    'overview.widget.conversion_today': 'Conversione di oggi',
    'overview.widget.sold_per_ride': 'Vendute per corsa',
    'overview.widget.rides_today': 'Corse di oggi',
    'overview.kiosk.chart_title': 'Ricavi',
    'overview.kiosk.chart_subtitle': 'Ricavi giornalieri del chiosco',
    'overview.kiosk.chart_revenue': 'Ricavi',
    'overview.flow.title': 'Flusso ricavi',
    'overview.flow.subtitle': 'Vendite online e locali combinate negli ultimi 30 giorni',
    'overview.flow.payment_success': 'Pagamenti riusciti',
    'overview.activity.title': 'Avvisi e attività',
    'overview.activity.subtitle': 'Avvisi live, risposte del supporto e segnali operativi recenti',
    'overview.activity.none': 'Nessun avviso o attività trovata.',
    'overview.activity.cleared': 'Tutti gli avvisi sono stati nascosti.',
    'overview.activity.support': 'Supporto',
    'overview.activity.stripe': 'Stripe',
    'overview.activity.ops': 'Ops',
    'overview.activity.clear': 'Rimuovi',
    'overview.recent_transactions': 'Transazioni recenti',
    'overview.recent_transactions.none': 'Nessuna transazione recente disponibile.',
    'overview.recent_transactions.show_less': 'Mostra meno',
    'overview.recent_transactions.show_all': 'Mostra tutte le {count}',
    'overview.kiosk.sale_title': 'Foto venduta al chiosco',
    'overview.kiosk.sale_claimed': 'Riscossa più tardi: {email}',
    'overview.kiosk.sale_unknown': 'Nessuno stato di ritiro noto',
    'overview.support_reply': 'Risposta supporto: {subject}',
    'overview.online_payment': 'Pagamento online',
    'overview.local_transaction': 'Transazione locale',
    'overview.local_sale': 'Vendita {method}',
    'overview.stripe_payment_fallback': 'Pagamento Stripe {id}',
    'revenue.subtitle_unified': 'Vista unificata dei ricavi online e locali',
    'revenue.partial_available': 'I ricavi sono disponibili solo parzialmente.',
    'revenue.no_feed_title': 'Nessun feed ricavi attivo',
    'revenue.no_feed_desc': 'Questo parco non ha al momento una fonte Stripe o vendite locali raggiungibile. La pagina si popolerà automaticamente non appena una fonte sarà disponibile.',
    'revenue.kiosk.title': 'Chiosco self-service',
    'revenue.kiosk.desc': 'Qui non esiste un webshop separato: ogni foto salvata è già un acquisto pagato al chiosco ({price} per foto).',
    'revenue.kpi.today': 'Oggi',
    'revenue.kpi.last_7_days': 'Ultimi 7 giorni',
    'revenue.kpi.this_month': 'Questo mese',
    'revenue.kpi.total_since_records': 'Totale (dall’inizio)',
    'revenue.kpi.rides_today': 'Corse oggi',
    'revenue.kpi.camera_captures_today': 'Scatti camera oggi',
    'revenue.kpi.conversion_today': 'Conversione oggi',
    'revenue.kpi.sold_per_ride': 'Vendute per corsa',
    'revenue.kpi.total_revenue': 'Ricavi totali',
    'revenue.kpi.total_transactions': 'Transazioni totali',
    'revenue.section.revenue': 'Ricavi',
    'revenue.section.daily_machine': 'Ricavi giornalieri del chiosco',
    'revenue.section.hourly': 'Ricavi per ora',
    'revenue.tab.total': 'Totale',
    'revenue.tab.today': 'Oggi',
    'revenue.tab.yesterday': 'Ieri',
    'revenue.tab.other_day': 'Altro giorno',
    'revenue.previous_day': 'Giorno precedente',
    'revenue.next_day': 'Giorno successivo',
    'revenue.select_day': 'Seleziona giorno',
    'revenue.day_revenue': 'Ricavi del {date}',
    'revenue.photos_sold': '{count} foto vendute',
    'revenue.loading': 'Caricamento...',
    'revenue.no_sales': 'Nessuna vendita in questo giorno.',
    'revenue.legend.revenue': 'Ricavi',
    'revenue.legend.rides': 'Corse',
    'revenue.daily_overview': 'Panoramica giornaliera',
    'revenue.no_sales_data': 'Nessun dato di vendita registrato finora.',
    'revenue.table.day': 'Giorno',
    'revenue.table.sold': 'Vendute',
    'revenue.table.rides': 'Corse',
    'revenue.table.rate': 'Tasso',
    'revenue.table.revenue': 'Ricavi',
    'revenue.online_commerce.title': 'Area commercio online',
    'revenue.online_commerce.subtitle': 'I ricavi Stripe e gli acquisti online restano separati dalla telemetria della macchina.',
    'revenue.online_commerce.confirmed_revenue': 'Ricavi online confermati: {value}',
    'revenue.online_commerce.successful_payments': 'Pagamenti online riusciti: {value}',
    'revenue.local_operations.title': 'Area operativa locale',
    'revenue.local_operations.subtitle': 'Solo gli importi locali confermati contano come ricavo. Importi rilevati o sconosciuti restano fuori dai totali.',
    'revenue.local_operations.confirmed_revenue': 'Ricavi locali confermati: {value}',
    'revenue.local_operations.detected_unconfirmed': 'Importo locale rilevato ma non confermato: {value}',
    'revenue.local_operations.unknown_signals': 'Segnali locali senza importo: {value}',
    'revenue.trend.title': 'Trend ricavi',
    'revenue.trend.subtitle': 'Ultimi 30 giorni, solo ricavi online e locali confermati',
    'revenue.breakdown.title': 'Ripartizione vendite locali',
    'revenue.breakdown.subtitle': 'Qui vengono mostrati solo importi locali confermati in contanti e terminale.',
    'revenue.signals.title': 'Segnali di vendita',
    'revenue.signals.payment_attempts': 'Tentativi di pagamento',
    'revenue.signals.success_rate': 'Tasso di successo',
    'revenue.signals.cancel_rate': 'Tasso di annullamento',
    'revenue.signals.cash_transactions': 'Transazioni contanti / monete',
    'revenue.signals.terminal_transactions': 'Transazioni terminale',
    'revenue.signals.unconfirmed_local_sales': 'Vendite locali non confermate',
    'revenue.signals.unknown_local_amounts': 'Importi locali sconosciuti',
    'revenue.legend.online': 'Online',
    'revenue.legend.local': 'Locale',
    'revenue.cash': 'Contanti',
    'revenue.terminal': 'Terminale',
    'revenue.detected_unconfirmed': 'Rilevato, non confermato: {value}',
    'revenue.local_display.detected': '{value} rilevati',
    'revenue.local_display.unknown': 'Sconosciuto',
    'revenue.local_display.confirmed_only': 'Solo ricavi locali confermati',
    'revenue.local_display.detected_only': 'Rilevato nei dati macchina, ma non confermato come ricavo',
    'revenue.local_display.unknown_only': 'Esiste attività di vendita locale senza importo confermato',
    'revenue.local_display.none_yet': 'Nessun ricavo locale confermato finora',
    'purchases.subtitle_kiosk': 'Ogni foto degli ultimi ~30 giorni acquistata al chiosco',
    'purchases.subtitle_unified': 'Registro unificato di transazioni Stripe e vendite sul posto',
    'purchases.partial_available': 'I dati delle transazioni sono disponibili solo parzialmente.',
    'purchases.table.source': 'Fonte',
    'purchases.table.customer_device': 'Cliente / Dispositivo',
    'purchases.table.payment': 'Pagamento',
    'purchases.table.description': 'Descrizione',
    'purchases.source.online': 'Online',
    'purchases.source.local': 'Locale',
    'purchases.source.kiosk': 'Chiosco',
    'purchases.source.automaton': 'Chiosco',
    'purchases.customer.stripe': 'Cliente Stripe',
    'purchases.customer.local_device': 'Dispositivo locale',
    'purchases.customer.unknown': 'Sconosciuto',
    'purchases.status.claimed': 'Riscossa',
    'purchases.amount.detected': 'Rilevato, non confermato',
    'purchases.amount.none': 'Nessun importo confermato',
    'purchases.filter.all': 'Tutte le fonti',
    'purchases.filter.online': 'Solo online',
    'purchases.filter.local': 'Solo locale',
    'purchases.description.kiosk_bought': 'Foto acquistata al chiosco',
    'purchases.description.kiosk_claimed': 'Foto acquistata al chiosco e riscossa più tardi via QR ({email})',
    'photos.error_loading': 'Errore nel caricamento delle foto',
    'photos.data_unavailable': 'I dati foto non sono attualmente disponibili.',
    'photos.for_day': 'Analisi per {date}',
    'photos.for_day_desc': 'Riquadri e cerchi si riferiscono a questo giorno',
    'photos.previous_day': 'Giorno precedente',
    'photos.next_day': 'Giorno successivo',
    'photos.today': 'Oggi',
    'photos.subtitle.day_captures': 'Scatti · {date}',
    'photos.subtitle.sold_total': '{count} totali',
    'photos.subtitle.on_that_day': 'in quel giorno',
    'photos.expired': 'Scadute',
    'photos.conversion_chart': 'Conversione',
    'photos.not_purchased': 'Non acquistate',
    'photos.rides_without_purchase': 'Corse senza acquisto',
    'photos.of_rides': 'su {count} corse',
    'photos.by_attraction.none': 'Per questo giorno non sono ancora disponibili dati per attrazione.',
    'photos.by_attraction.captures': '{count} scatti',
    'photos.by_attraction.sold': '{count} vendute',
    'photos.email_capture': 'Raccolta e-mail',
    'photos.email_capture.buyers': '{given} di {total} acquirenti',
    'photos.email_capture.none': 'Nessun acquisto in questo giorno',
    'photos.browser.title': 'Browser foto',
    'photos.browser.refresh': 'Aggiorna',
    'photos.browser.search_code': 'Inserisci numero foto…',
    'photos.browser.search': 'Cerca',
    'photos.browser.reset': 'Reimposta ricerca',
    'photos.browser.none': 'Nessuna foto trovata.',
    'photos.browser.status.purchased': 'acquistata',
    'photos.browser.status.available': 'disponibile',
    'photos.browser.photo_alt': 'Foto',
    'photos.browser.selected_alt': 'Foto selezionata',
    'photos.browser.copy_claim': 'Copia link claim',
    'photos.browser.copy_image': 'Copia link immagine',
    'photos.browser.copied': 'Copiato!',
    'photos.browser.claim_explainer': 'Link claim: il cliente lo apre e recupera la foto via e-mail (anche se il QR stampato era errato). Link immagine: download diretto.',
    'photos.browser.select_prompt': 'Seleziona una foto per visualizzarla grande qui.',
  },
  nl: {
    'kpi.vs_last_week': 'vs vorige week',
    'overview.last_data': 'Laatste data {time}',
    'overview.badge.stripe_enabled': 'Stripe actief',
    'overview.badge.local_sales_active': 'Lokale verkoop actief',
    'overview.badge.printer_telemetry': 'Printertelemetrie',
    'overview.partial_data': 'Sommige databronnen zijn momenteel niet beschikbaar.',
    'overview.kiosk.revenue_today': 'Omzet vandaag',
    'overview.kiosk.photos_sold_today': 'Foto’s verkocht vandaag',
    'overview.kiosk.photo_paper': 'Fotopapier',
    'overview.kiosk.photos_sold_month': 'Foto’s verkocht (maand)',
    'overview.kiosk.revenue_month': 'Omzet (maand)',
    'overview.kiosk.photos_sold_total': 'Foto’s verkocht (totaal)',
    'overview.online_revenue': 'Online omzet',
    'overview.local_revenue': 'Lokale omzet',
    'overview.transactions': 'Transacties',
    'overview.errors': 'Fouten',
    'overview.warnings': 'Waarschuwingen',
    'overview.paper_remaining': 'Papier resterend',
    'overview.print_count': 'Aantal prints',
    'overview.widget.last_activity': 'Laatste activiteit',
    'overview.widget.open_system_health': 'Systeemstatus openen',
    'overview.widget.data_files_scanned': 'Databestanden gescand',
    'overview.widget.recognized_ops_files': 'Herkenbare operationele bestanden',
    'overview.widget.open_operations': 'Operations openen',
    'overview.widget.users': 'Gebruikers',
    'overview.widget.open_users': 'Gebruikers openen',
    'overview.widget.photos': 'Foto’s',
    'overview.widget.open_photos': 'Foto’s openen',
    'overview.widget.active_attractions': 'Actieve attracties',
    'overview.widget.conversion_today': 'Conversie vandaag',
    'overview.widget.sold_per_ride': 'Verkocht per rit',
    'overview.widget.rides_today': 'Ritten vandaag',
    'overview.kiosk.chart_title': 'Omzet',
    'overview.kiosk.chart_subtitle': 'Dagelijkse kiosk-omzet',
    'overview.kiosk.chart_revenue': 'Omzet',
    'overview.flow.title': 'Omzetstroom',
    'overview.flow.subtitle': 'Online en lokale verkopen gecombineerd over de laatste 30 dagen',
    'overview.flow.payment_success': 'Betaalsucces',
    'overview.activity.title': 'Waarschuwingen & activiteit',
    'overview.activity.subtitle': 'Live-waarschuwingen, support-updates en recente operationele signalen',
    'overview.activity.none': 'Geen waarschuwingen of activiteit gevonden.',
    'overview.activity.cleared': 'Alle waarschuwingen zijn verborgen.',
    'overview.activity.support': 'Support',
    'overview.activity.stripe': 'Stripe',
    'overview.activity.ops': 'Ops',
    'overview.activity.clear': 'Verwijderen',
    'overview.recent_transactions': 'Recente transacties',
    'overview.recent_transactions.none': 'Geen recente transacties beschikbaar.',
    'overview.recent_transactions.show_less': 'Minder tonen',
    'overview.recent_transactions.show_all': 'Toon alle {count}',
    'overview.kiosk.sale_title': 'Foto verkocht bij kiosk',
    'overview.kiosk.sale_claimed': 'Later opgehaald: {email}',
    'overview.kiosk.sale_unknown': 'Geen ophaalstatus bekend',
    'overview.support_reply': 'Support-reactie: {subject}',
    'overview.online_payment': 'Online betaling',
    'overview.local_transaction': 'Lokale transactie',
    'overview.local_sale': '{method}-verkoop',
    'overview.stripe_payment_fallback': 'Stripe-betaling {id}',
    'revenue.subtitle_unified': 'Gecombineerd omzetoverzicht voor online en lokale verkopen',
    'revenue.partial_available': 'Omzet is slechts gedeeltelijk beschikbaar.',
    'revenue.no_feed_title': 'Geen actieve omzetfeed',
    'revenue.no_feed_desc': 'Voor dit park is momenteel geen Stripe- of lokale verkoopbron bereikbaar. De pagina vult zich automatisch zodra een feed beschikbaar is.',
    'revenue.kiosk.title': 'Selfservice-kiosk',
    'revenue.kiosk.desc': 'Er is hier geen aparte webshop — elke opgeslagen foto is al een betaalde kiosk-aankoop ({price} per foto).',
    'revenue.kpi.today': 'Vandaag',
    'revenue.kpi.last_7_days': 'Laatste 7 dagen',
    'revenue.kpi.this_month': 'Deze maand',
    'revenue.kpi.total_since_records': 'Totaal (sinds start registratie)',
    'revenue.kpi.rides_today': 'Ritten vandaag',
    'revenue.kpi.camera_captures_today': 'Camera-opnames vandaag',
    'revenue.kpi.conversion_today': 'Conversie vandaag',
    'revenue.kpi.sold_per_ride': 'Verkocht per rit',
    'revenue.kpi.total_revenue': 'Totale omzet',
    'revenue.kpi.total_transactions': 'Totale transacties',
    'revenue.section.revenue': 'Omzet',
    'revenue.section.daily_machine': 'Dagelijkse kiosk-omzet',
    'revenue.section.hourly': 'Omzet per uur',
    'revenue.tab.total': 'Totaal',
    'revenue.tab.today': 'Vandaag',
    'revenue.tab.yesterday': 'Gisteren',
    'revenue.tab.other_day': 'Andere dag',
    'revenue.previous_day': 'Vorige dag',
    'revenue.next_day': 'Volgende dag',
    'revenue.select_day': 'Dag kiezen',
    'revenue.day_revenue': 'Omzet op {date}',
    'revenue.photos_sold': '{count} foto’s verkocht',
    'revenue.loading': 'Laden...',
    'revenue.no_sales': 'Geen verkopen op deze dag.',
    'revenue.legend.revenue': 'Omzet',
    'revenue.legend.rides': 'Ritten',
    'revenue.daily_overview': 'Dagtotaal',
    'revenue.no_sales_data': 'Nog geen verkoopdata geregistreerd.',
    'revenue.table.day': 'Dag',
    'revenue.table.sold': 'Verkocht',
    'revenue.table.rides': 'Ritten',
    'revenue.table.rate': 'Ratio',
    'revenue.table.revenue': 'Omzet',
    'revenue.online_commerce.title': 'Online-commercegebied',
    'revenue.online_commerce.subtitle': 'Stripe-omzet en online aankopen blijven gescheiden van machine-telemetrie.',
    'revenue.online_commerce.confirmed_revenue': 'Bevestigde online omzet: {value}',
    'revenue.online_commerce.successful_payments': 'Succesvolle online betalingen: {value}',
    'revenue.local_operations.title': 'Lokale operations',
    'revenue.local_operations.subtitle': 'Alleen bevestigde lokale bedragen tellen als omzet. Gedetecteerde of onbekende bedragen vallen buiten de totalen.',
    'revenue.local_operations.confirmed_revenue': 'Bevestigde lokale omzet: {value}',
    'revenue.local_operations.detected_unconfirmed': 'Gedetecteerd maar onbevestigd lokaal bedrag: {value}',
    'revenue.local_operations.unknown_signals': 'Lokale signalen zonder bedrag: {value}',
    'revenue.trend.title': 'Omzettrend',
    'revenue.trend.subtitle': 'Laatste 30 dagen, alleen bevestigde online en lokale omzet',
    'revenue.breakdown.title': 'Uitsplitsing lokale verkoop',
    'revenue.breakdown.subtitle': 'Hier worden alleen bevestigde lokale contante en terminalbedragen getoond.',
    'revenue.signals.title': 'Verkoopsignalen',
    'revenue.signals.payment_attempts': 'Betaalpogingen',
    'revenue.signals.success_rate': 'Succespercentage',
    'revenue.signals.cancel_rate': 'Annuleringspercentage',
    'revenue.signals.cash_transactions': 'Contante / munttransacties',
    'revenue.signals.terminal_transactions': 'Terminaltransacties',
    'revenue.signals.unconfirmed_local_sales': 'Onbevestigde lokale verkopen',
    'revenue.signals.unknown_local_amounts': 'Onbekende lokale bedragen',
    'revenue.legend.online': 'Online',
    'revenue.legend.local': 'Lokaal',
    'revenue.cash': 'Contant',
    'revenue.terminal': 'Terminal',
    'revenue.detected_unconfirmed': 'Gedetecteerd, onbevestigd: {value}',
    'revenue.local_display.detected': '{value} gedetecteerd',
    'revenue.local_display.unknown': 'Onbekend',
    'revenue.local_display.confirmed_only': 'Alleen bevestigde lokale omzet',
    'revenue.local_display.detected_only': 'Gedetecteerd in machinedata, maar niet bevestigd als omzet',
    'revenue.local_display.unknown_only': 'Er is lokale verkoopactiviteit zonder bevestigd bedrag',
    'revenue.local_display.none_yet': 'Nog geen bevestigde lokale omzet',
    'purchases.subtitle_kiosk': 'Elke foto van de laatste ~30 dagen die bij de kiosk is gekocht',
    'purchases.subtitle_unified': 'Gecombineerd transactielogboek voor Stripe en lokale verkopen',
    'purchases.partial_available': 'Transactiegegevens zijn slechts gedeeltelijk beschikbaar.',
    'purchases.table.source': 'Bron',
    'purchases.table.customer_device': 'Klant / Apparaat',
    'purchases.table.payment': 'Betaling',
    'purchases.table.description': 'Beschrijving',
    'purchases.source.online': 'Online',
    'purchases.source.local': 'Lokaal',
    'purchases.source.kiosk': 'Kiosk',
    'purchases.source.automaton': 'Kiosk',
    'purchases.customer.stripe': 'Stripe-klant',
    'purchases.customer.local_device': 'Lokaal apparaat',
    'purchases.customer.unknown': 'Onbekend',
    'purchases.status.claimed': 'Opgehaald',
    'purchases.amount.detected': 'Gedetecteerd, niet bevestigd',
    'purchases.amount.none': 'Geen bevestigd bedrag',
    'purchases.filter.all': 'Alle bronnen',
    'purchases.filter.online': 'Alleen online',
    'purchases.filter.local': 'Alleen lokaal',
    'purchases.description.kiosk_bought': 'Foto gekocht bij de kiosk',
    'purchases.description.kiosk_claimed': 'Foto gekocht bij kiosk en later via QR opgehaald ({email})',
    'photos.error_loading': 'Fout bij laden van foto’s',
    'photos.data_unavailable': 'Fotodata is momenteel niet beschikbaar.',
    'photos.for_day': 'Analyse voor {date}',
    'photos.for_day_desc': 'Tegels en cirkels hebben betrekking op deze dag',
    'photos.previous_day': 'Vorige dag',
    'photos.next_day': 'Volgende dag',
    'photos.today': 'Vandaag',
    'photos.subtitle.day_captures': 'Opnames · {date}',
    'photos.subtitle.sold_total': '{count} totaal',
    'photos.subtitle.on_that_day': 'op die dag',
    'photos.expired': 'Verlopen',
    'photos.conversion_chart': 'Conversie',
    'photos.not_purchased': 'Niet gekocht',
    'photos.rides_without_purchase': 'Ritten zonder aankoop',
    'photos.of_rides': 'van {count} ritten',
    'photos.by_attraction.none': 'Voor deze dag zijn nog geen attractiedata beschikbaar.',
    'photos.by_attraction.captures': '{count} opnames',
    'photos.by_attraction.sold': '{count} verkocht',
    'photos.email_capture': 'E-mailregistratie',
    'photos.email_capture.buyers': '{given} van {total} kopers',
    'photos.email_capture.none': 'Geen aankopen op deze dag',
    'photos.browser.title': 'Foto-browser',
    'photos.browser.refresh': 'Vernieuwen',
    'photos.browser.search_code': 'Voer fotonummer in…',
    'photos.browser.search': 'Zoeken',
    'photos.browser.reset': 'Zoekopdracht wissen',
    'photos.browser.none': 'Geen foto’s gevonden.',
    'photos.browser.status.purchased': 'gekocht',
    'photos.browser.status.available': 'beschikbaar',
    'photos.browser.photo_alt': 'Foto',
    'photos.browser.selected_alt': 'Geselecteerde foto',
    'photos.browser.copy_claim': 'Claim-link kopiëren',
    'photos.browser.copy_image': 'Afbeeldingslink kopiëren',
    'photos.browser.copied': 'Gekopieerd!',
    'photos.browser.claim_explainer': 'Claim-link: de klant opent deze en haalt de foto op via e-mail (ook als de geprinte QR fout was). Afbeeldingslink: directe download.',
    'photos.browser.select_prompt': 'Selecteer een foto om die hier groot te tonen.',
  },
  lv: {
    'kpi.vs_last_week': 'salīdzinot ar iepriekšējo nedēļu',
    'overview.last_data': 'Pēdējie dati {time}',
    'overview.badge.stripe_enabled': 'Stripe aktīvs',
    'overview.badge.local_sales_active': 'Vietējā pārdošana aktīva',
    'overview.badge.printer_telemetry': 'Printera telemetrija',
    'overview.partial_data': 'Daži datu avoti pašlaik nav pieejami.',
    'overview.kiosk.revenue_today': 'Ieņēmumi šodien',
    'overview.kiosk.photos_sold_today': 'Šodien pārdotie foto',
    'overview.kiosk.photo_paper': 'Fotopapīrs',
    'overview.kiosk.photos_sold_month': 'Pārdotie foto (mēnesis)',
    'overview.kiosk.revenue_month': 'Ieņēmumi (mēnesis)',
    'overview.kiosk.photos_sold_total': 'Pārdotie foto (kopā)',
    'overview.online_revenue': 'Tiešsaistes ieņēmumi',
    'overview.local_revenue': 'Vietējie ieņēmumi',
    'overview.transactions': 'Darījumi',
    'overview.errors': 'Kļūdas',
    'overview.warnings': 'Brīdinājumi',
    'overview.paper_remaining': 'Atlikušais papīrs',
    'overview.print_count': 'Izdruku skaits',
    'overview.widget.last_activity': 'Pēdējā aktivitāte',
    'overview.widget.open_system_health': 'Atvērt sistēmas stāvokli',
    'overview.widget.data_files_scanned': 'Skenētie datu faili',
    'overview.widget.recognized_ops_files': 'Atpazītie darbības faili',
    'overview.widget.open_operations': 'Atvērt operācijas',
    'overview.widget.users': 'Lietotāji',
    'overview.widget.open_users': 'Atvērt lietotājus',
    'overview.widget.photos': 'Foto',
    'overview.widget.open_photos': 'Atvērt foto',
    'overview.widget.active_attractions': 'Aktīvās atrakcijas',
    'overview.widget.conversion_today': 'Konversija šodien',
    'overview.widget.sold_per_ride': 'Pārdots uz braucienu',
    'overview.widget.rides_today': 'Braucieni šodien',
    'overview.kiosk.chart_title': 'Ieņēmumi',
    'overview.kiosk.chart_subtitle': 'Dienas ieņēmumi kioskā',
    'overview.kiosk.chart_revenue': 'Ieņēmumi',
    'overview.flow.title': 'Ieņēmumu plūsma',
    'overview.flow.subtitle': 'Pēdējo 30 dienu tiešsaistes un vietējie pārdošanas dati kopā',
    'overview.flow.payment_success': 'Maksājumu veiksme',
    'overview.activity.title': 'Brīdinājumi un aktivitāte',
    'overview.activity.subtitle': 'Reāllaika brīdinājumi, atbalsta ziņas un jaunākie darbības signāli',
    'overview.activity.none': 'Nav atrastu brīdinājumu vai aktivitāšu.',
    'overview.activity.cleared': 'Visi brīdinājumi ir paslēpti.',
    'overview.activity.support': 'Atbalsts',
    'overview.activity.stripe': 'Stripe',
    'overview.activity.ops': 'Darbība',
    'overview.activity.clear': 'Noņemt',
    'overview.recent_transactions': 'Jaunākie darījumi',
    'overview.recent_transactions.none': 'Nav pieejamu nesenu darījumu.',
    'overview.recent_transactions.show_less': 'Rādīt mazāk',
    'overview.recent_transactions.show_all': 'Rādīt visus {count}',
    'overview.kiosk.sale_title': 'Foto pārdots kioskā',
    'overview.kiosk.sale_claimed': 'Paņemts vēlāk: {email}',
    'overview.kiosk.sale_unknown': 'Nav zināms saņemšanas statuss',
    'overview.support_reply': 'Atbalsta atbilde: {subject}',
    'overview.online_payment': 'Tiešsaistes maksājums',
    'overview.local_transaction': 'Vietējais darījums',
    'overview.local_sale': '{method} pārdošana',
    'overview.stripe_payment_fallback': 'Stripe maksājums {id}',
    'revenue.subtitle_unified': 'Vienots ieņēmumu skats tiešsaistes un vietējiem pārdošanas datiem',
    'revenue.partial_available': 'Ieņēmumu dati ir pieejami tikai daļēji.',
    'revenue.no_feed_title': 'Nav aktīva ieņēmumu plūsmas',
    'revenue.no_feed_desc': 'Šim parkam pašlaik nav sasniedzama Stripe vai vietējās pārdošanas avota. Lapa piepildīsies automātiski, tiklīdz kāds avots būs pieejams.',
    'revenue.kiosk.title': 'Pašapkalpošanās kiosks',
    'revenue.kiosk.desc': 'Šeit nav atsevišķa interneta veikala — katrs saglabātais foto jau ir apmaksāts pirkums kioskā ({price} par foto).',
    'revenue.kpi.today': 'Šodien',
    'revenue.kpi.last_7_days': 'Pēdējās 7 dienas',
    'revenue.kpi.this_month': 'Šis mēnesis',
    'revenue.kpi.total_since_records': 'Kopā (kopš uzskaites sākuma)',
    'revenue.kpi.rides_today': 'Braucieni šodien',
    'revenue.kpi.camera_captures_today': 'Kameras uzņemumi šodien',
    'revenue.kpi.conversion_today': 'Konversija šodien',
    'revenue.kpi.sold_per_ride': 'Pārdots uz braucienu',
    'revenue.kpi.total_revenue': 'Kopējie ieņēmumi',
    'revenue.kpi.total_transactions': 'Kopējie darījumi',
    'revenue.section.revenue': 'Ieņēmumi',
    'revenue.section.daily_machine': 'Dienas ieņēmumi kioskā',
    'revenue.section.hourly': 'Ieņēmumi pa stundām',
    'revenue.tab.total': 'Kopā',
    'revenue.tab.today': 'Šodien',
    'revenue.tab.yesterday': 'Vakar',
    'revenue.tab.other_day': 'Cita diena',
    'revenue.previous_day': 'Iepriekšējā diena',
    'revenue.next_day': 'Nākamā diena',
    'revenue.select_day': 'Izvēlēties dienu',
    'revenue.day_revenue': 'Ieņēmumi {date}',
    'revenue.photos_sold': 'Pārdoti {count} foto',
    'revenue.loading': 'Ielādē...',
    'revenue.no_sales': 'Šajā dienā pārdošanas nebija.',
    'revenue.legend.revenue': 'Ieņēmumi',
    'revenue.legend.rides': 'Braucieni',
    'revenue.daily_overview': 'Dienas pārskats',
    'revenue.no_sales_data': 'Pārdošanas dati vēl nav reģistrēti.',
    'revenue.table.day': 'Diena',
    'revenue.table.sold': 'Pārdots',
    'revenue.table.rides': 'Braucieni',
    'revenue.table.rate': 'Rādītājs',
    'revenue.table.revenue': 'Ieņēmumi',
    'revenue.online_commerce.title': 'Tiešsaistes tirdzniecības daļa',
    'revenue.online_commerce.subtitle': 'Stripe ieņēmumi un tiešsaistes pirkumi tiek turēti atsevišķi no iekārtas telemetrijas.',
    'revenue.online_commerce.confirmed_revenue': 'Apstiprinātie tiešsaistes ieņēmumi: {value}',
    'revenue.online_commerce.successful_payments': 'Veiksmīgie tiešsaistes maksājumi: {value}',
    'revenue.local_operations.title': 'Vietējo operāciju daļa',
    'revenue.local_operations.subtitle': 'Tikai apstiprinātās vietējās summas tiek skaitītas kā ieņēmumi. Atrastās vai nezināmās summas paliek ārpus kopsummām.',
    'revenue.local_operations.confirmed_revenue': 'Apstiprinātie vietējie ieņēmumi: {value}',
    'revenue.local_operations.detected_unconfirmed': 'Atrasta, bet neapstiprināta vietējā summa: {value}',
    'revenue.local_operations.unknown_signals': 'Vietējie signāli bez summas: {value}',
    'revenue.trend.title': 'Ieņēmumu tendence',
    'revenue.trend.subtitle': 'Pēdējās 30 dienas, tikai apstiprinātie tiešsaistes un vietējie ieņēmumi',
    'revenue.breakdown.title': 'Vietējo pārdošanu sadalījums',
    'revenue.breakdown.subtitle': 'Šeit tiek attēlotas tikai apstiprinātas vietējās skaidras naudas un termināļa summas.',
    'revenue.signals.title': 'Pārdošanas signāli',
    'revenue.signals.payment_attempts': 'Maksājumu mēģinājumi',
    'revenue.signals.success_rate': 'Veiksmes rādītājs',
    'revenue.signals.cancel_rate': 'Atcelšanas rādītājs',
    'revenue.signals.cash_transactions': 'Skaidras naudas / monētu darījumi',
    'revenue.signals.terminal_transactions': 'Termināļa darījumi',
    'revenue.signals.unconfirmed_local_sales': 'Neapstiprināti vietējie pārdojumi',
    'revenue.signals.unknown_local_amounts': 'Nezināmas vietējās summas',
    'revenue.legend.online': 'Tiešsaistē',
    'revenue.legend.local': 'Vietēji',
    'revenue.cash': 'Skaidra nauda',
    'revenue.terminal': 'Terminālis',
    'revenue.detected_unconfirmed': 'Atrasts, bet neapstiprināts: {value}',
    'revenue.local_display.detected': '{value} atrasti',
    'revenue.local_display.unknown': 'Nezināms',
    'revenue.local_display.confirmed_only': 'Tikai apstiprinātie vietējie ieņēmumi',
    'revenue.local_display.detected_only': 'Atrasts iekārtas datos, bet nav apstiprināts kā ieņēmumi',
    'revenue.local_display.unknown_only': 'Ir vietējā pārdošanas aktivitāte bez apstiprinātas summas',
    'revenue.local_display.none_yet': 'Vēl nav apstiprinātu vietējo ieņēmumu',
    'purchases.subtitle_kiosk': 'Katrs foto no pēdējām ~30 dienām, kas nopirkts kioskā',
    'purchases.subtitle_unified': 'Vienots Stripe un vietējo pārdošanu darījumu žurnāls',
    'purchases.partial_available': 'Darījumu dati ir pieejami tikai daļēji.',
    'purchases.table.source': 'Avots',
    'purchases.table.customer_device': 'Klients / Ierīce',
    'purchases.table.payment': 'Maksājums',
    'purchases.table.description': 'Apraksts',
    'purchases.source.online': 'Tiešsaistē',
    'purchases.source.local': 'Vietēji',
    'purchases.source.kiosk': 'Kiosks',
    'purchases.source.automaton': 'Kiosks',
    'purchases.customer.stripe': 'Stripe klients',
    'purchases.customer.local_device': 'Vietējā ierīce',
    'purchases.customer.unknown': 'Nezināms',
    'purchases.status.claimed': 'Paņemts',
    'purchases.amount.detected': 'Atrasts, neapstiprināts',
    'purchases.amount.none': 'Nav apstiprinātas summas',
    'purchases.filter.all': 'Visi avoti',
    'purchases.filter.online': 'Tikai tiešsaistē',
    'purchases.filter.local': 'Tikai vietēji',
    'purchases.description.kiosk_bought': 'Foto nopirkts kioskā',
    'purchases.description.kiosk_claimed': 'Foto nopirkts kioskā un vēlāk paņemts ar QR kodu ({email})',
    'photos.error_loading': 'Kļūda, ielādējot foto',
    'photos.data_unavailable': 'Foto dati pašlaik nav pieejami.',
    'photos.for_day': 'Analīze par {date}',
    'photos.for_day_desc': 'Flīzes un apļi attiecas uz šo dienu',
    'photos.previous_day': 'Iepriekšējā diena',
    'photos.next_day': 'Nākamā diena',
    'photos.today': 'Šodien',
    'photos.subtitle.day_captures': 'Uzņemumi · {date}',
    'photos.subtitle.sold_total': '{count} kopā',
    'photos.subtitle.on_that_day': 'šajā dienā',
    'photos.expired': 'Beidzies termiņš',
    'photos.conversion_chart': 'Konversija',
    'photos.not_purchased': 'Nav nopirkts',
    'photos.rides_without_purchase': 'Braucieni bez pirkuma',
    'photos.of_rides': 'no {count} braucieniem',
    'photos.by_attraction.none': 'Šai dienai vēl nav pieejamu atrakciju datu.',
    'photos.by_attraction.captures': '{count} uzņemumi',
    'photos.by_attraction.sold': '{count} pārdoti',
    'photos.email_capture': 'E-pasta iegūšana',
    'photos.email_capture.buyers': '{given} no {total} pircējiem',
    'photos.email_capture.none': 'Šajā dienā pirkumu nebija',
    'photos.browser.title': 'Foto pārlūks',
    'photos.browser.refresh': 'Atsvaidzināt',
    'photos.browser.search_code': 'Ievadi foto numuru…',
    'photos.browser.search': 'Meklēt',
    'photos.browser.reset': 'Atiestatīt meklēšanu',
    'photos.browser.none': 'Foto nav atrasti.',
    'photos.browser.status.purchased': 'nopirkts',
    'photos.browser.status.available': 'pieejams',
    'photos.browser.photo_alt': 'Foto',
    'photos.browser.selected_alt': 'Atlasītais foto',
    'photos.browser.copy_claim': 'Kopēt claim saiti',
    'photos.browser.copy_image': 'Kopēt attēla saiti',
    'photos.browser.copied': 'Nokopēts!',
    'photos.browser.claim_explainer': 'Claim saite: klients to atver un saņem savu foto pa e-pastu (pat ja drukātais QR bija nepareizs). Attēla saite: tieša lejupielāde.',
    'photos.browser.select_prompt': 'Izvēlies foto, lai to šeit redzētu lielāku.',
  },
};

export function getOperatorUiText(language: Language, key: OperatorUiKey, vars?: OperatorUiVars): string {
  const template = copy[language]?.[key] ?? copy.en[key] ?? key;
  if (!vars) return template;
  return template.replace(/\{(\w+)\}/g, (_, token: string) => String(vars[token] ?? ''));
}
