/*\n  # Remove Authentication and Enable Public Access\n\n  ## Changes Made\n\n  1. **Remove All Existing RLS Policies**\n     - Drop all policies from profiles, datasets, countries, leads, and activities tables\n\n  2. **Create Public Access Policies**\n     - profiles: Public can view all profiles\n     - datasets: Public can view, create, update, delete datasets\n     - countries: Public can view and update countries\n     - leads: Public can view, create, update, delete leads\n     - activities: Public can view, create, update, delete activities\n\n  ## Security Notes\n     - This migration removes all authentication requirements\n     - All data is now publicly accessible without login\n     - RLS is kept enabled but allows anonymous access\n*/\n\n-- ============================================\n-- DROP ALL EXISTING POLICIES\n-- ============================================\n\n-- Profiles policies\nDROP POLICY IF EXISTS "Users can view own profile" ON profiles;
\nDROP POLICY IF EXISTS "Users can update own profile" ON profiles;
\nDROP POLICY IF EXISTS "Admins can view all profiles" ON profiles;
\nDROP POLICY IF EXISTS "Admins can update all profiles" ON profiles;
\n\n-- Datasets policies\nDROP POLICY IF EXISTS "Authenticated users can view datasets" ON datasets;
\nDROP POLICY IF EXISTS "Admin and sales can create datasets" ON datasets;
\nDROP POLICY IF EXISTS "Admin can update datasets" ON datasets;
\nDROP POLICY IF EXISTS "Admin can delete datasets" ON datasets;
\n\n-- Countries policies\nDROP POLICY IF EXISTS "Authenticated users can view countries" ON countries;
\nDROP POLICY IF EXISTS "Admin and sales can update countries" ON countries;
\n\n-- Leads policies\nDROP POLICY IF EXISTS "Authenticated users can view leads" ON leads;
\nDROP POLICY IF EXISTS "Admin and sales can create leads" ON leads;
\nDROP POLICY IF EXISTS "Admin and sales can update leads" ON leads;
\nDROP POLICY IF EXISTS "Admin can delete leads" ON leads;
\n\n-- Activities policies\nDROP POLICY IF EXISTS "Authenticated users can view activities" ON activities;
\nDROP POLICY IF EXISTS "Admin and sales can create activities" ON activities;
\nDROP POLICY IF EXISTS "Users can update own activities" ON activities;
\nDROP POLICY IF EXISTS "Admin can delete activities" ON activities;
\n\n-- ============================================\n-- CREATE PUBLIC ACCESS POLICIES\n-- ============================================\n\n-- Profiles: Public read access\nCREATE POLICY "Public can view all profiles"\n  ON profiles FOR SELECT\n  TO anon, authenticated\n  USING (true);
\n\n-- Datasets: Full public access\nCREATE POLICY "Public can view datasets"\n  ON datasets FOR SELECT\n  TO anon, authenticated\n  USING (true);
\n\nCREATE POLICY "Public can create datasets"\n  ON datasets FOR INSERT\n  TO anon, authenticated\n  WITH CHECK (true);
\n\nCREATE POLICY "Public can update datasets"\n  ON datasets FOR UPDATE\n  TO anon, authenticated\n  USING (true)\n  WITH CHECK (true);
\n\nCREATE POLICY "Public can delete datasets"\n  ON datasets FOR DELETE\n  TO anon, authenticated\n  USING (true);
\n\n-- Countries: Full public access\nCREATE POLICY "Public can view countries"\n  ON countries FOR SELECT\n  TO anon, authenticated\n  USING (true);
\n\nCREATE POLICY "Public can update countries"\n  ON countries FOR UPDATE\n  TO anon, authenticated\n  USING (true)\n  WITH CHECK (true);
\n\n-- Leads: Full public access\nCREATE POLICY "Public can view leads"\n  ON leads FOR SELECT\n  TO anon, authenticated\n  USING (true);
\n\nCREATE POLICY "Public can create leads"\n  ON leads FOR INSERT\n  TO anon, authenticated\n  WITH CHECK (true);
\n\nCREATE POLICY "Public can update leads"\n  ON leads FOR UPDATE\n  TO anon, authenticated\n  USING (true)\n  WITH CHECK (true);
\n\nCREATE POLICY "Public can delete leads"\n  ON leads FOR DELETE\n  TO anon, authenticated\n  USING (true);
\n\n-- Activities: Full public access\nCREATE POLICY "Public can view activities"\n  ON activities FOR SELECT\n  TO anon, authenticated\n  USING (true);
\n\nCREATE POLICY "Public can create activities"\n  ON activities FOR INSERT\n  TO anon, authenticated\n  WITH CHECK (true);
\n\nCREATE POLICY "Public can update activities"\n  ON activities FOR UPDATE\n  TO anon, authenticated\n  USING (true)\n  WITH CHECK (true);
\n\nCREATE POLICY "Public can delete activities"\n  ON activities FOR DELETE\n  TO anon, authenticated\n  USING (true);
;
