/*\n  # Add User Authentication and Row Level Security\n\n  ## Overview\n  This migration implements comprehensive authentication and data isolation by:\n  - Adding user_id columns to tables that need user ownership\n  - Implementing restrictive RLS policies that ensure users only access their own data\n  - Creating proper indexes for performance\n  - Ensuring all data is properly scoped to authenticated users\n\n  ## Changes\n\n  ### 1. Schema Updates\n    - Add `user_id` column to `datasets` table\n    - Add `user_id` column to `email_templates` table\n    - Add indexes for user_id columns for query performance\n\n  ### 2. Row Level Security Policies\n\n  #### profiles table\n    - Users can read their own profile\n    - Users can insert their own profile (for signup)\n    - Users can update their own profile\n\n  #### datasets table\n    - Users can only view their own datasets\n    - Users can only insert datasets for themselves\n    - Users can only update their own datasets\n    - Users can only delete their own datasets\n\n  #### leads table\n    - Users can only view leads they own\n    - Users can only insert leads for themselves\n    - Users can only update their own leads\n    - Users can only delete their own leads\n\n  #### activities table\n    - Users can only view activities they created\n    - Users can only insert activities for themselves\n    - Users can only update their own activities\n    - Users can only delete their own activities\n\n  #### email_templates table\n    - Users can only view their own templates\n    - Users can only insert templates for themselves\n    - Users can only update their own templates\n    - Users can only delete their own templates\n\n  #### email_campaigns table\n    - Users can view campaigns they created\n    - Users can only insert campaigns for themselves\n    - Users can only update their own campaigns\n    - Users can only delete their own campaigns\n\n  #### email_sends and email_events tables\n    - Users can view sends/events for campaigns they created\n    - System can insert/update for email processing\n\n  #### countries table\n    - All authenticated users can read countries (reference data)\n    - Only admins can modify (handled at application level)\n\n  ## Important Notes\n  - All policies are restrictive by default\n  - Users MUST be authenticated to access any data\n  - Each user can ONLY access their own data\n  - The countries table is shared but read-only for all users\n*/\n\n-- Add user_id to datasets table\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'datasets' AND column_name = 'user_id'\n  ) THEN\n    ALTER TABLE datasets ADD COLUMN user_id uuid REFERENCES auth.users(id);
\n    CREATE INDEX IF NOT EXISTS idx_datasets_user_id ON datasets(user_id);
\n  END IF;
\nEND $$;
\n\n-- Add user_id to email_templates table\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'email_templates' AND column_name = 'user_id'\n  ) THEN\n    ALTER TABLE email_templates ADD COLUMN user_id uuid REFERENCES auth.users(id);
\n    CREATE INDEX IF NOT EXISTS idx_email_templates_user_id ON email_templates(user_id);
\n  END IF;
\nEND $$;
\n\n-- Add indexes for existing user reference columns\nCREATE INDEX IF NOT EXISTS idx_leads_owner_user_id ON leads(owner_user_id);
\nCREATE INDEX IF NOT EXISTS idx_activities_created_by ON activities(created_by);
\nCREATE INDEX IF NOT EXISTS idx_email_campaigns_created_by ON email_campaigns(created_by);
\n\n-- Drop all existing public access policies\nDROP POLICY IF EXISTS "Public can view all profiles" ON profiles;
\nDROP POLICY IF EXISTS "Public can view datasets" ON datasets;
\nDROP POLICY IF EXISTS "Public can create datasets" ON datasets;
\nDROP POLICY IF EXISTS "Public can update datasets" ON datasets;
\nDROP POLICY IF EXISTS "Public can delete datasets" ON datasets;
\nDROP POLICY IF EXISTS "Public can view countries" ON countries;
\nDROP POLICY IF EXISTS "Public can update countries" ON countries;
\nDROP POLICY IF EXISTS "Public can view leads" ON leads;
\nDROP POLICY IF EXISTS "Public can create leads" ON leads;
\nDROP POLICY IF EXISTS "Public can update leads" ON leads;
\nDROP POLICY IF EXISTS "Public can delete leads" ON leads;
\nDROP POLICY IF EXISTS "Public can view activities" ON activities;
\nDROP POLICY IF EXISTS "Public can create activities" ON activities;
\nDROP POLICY IF EXISTS "Public can update activities" ON activities;
\nDROP POLICY IF EXISTS "Public can delete activities" ON activities;
\nDROP POLICY IF EXISTS "Public read access" ON email_templates;
\nDROP POLICY IF EXISTS "Public write access" ON email_templates;
\nDROP POLICY IF EXISTS "Public read access" ON email_campaigns;
\nDROP POLICY IF EXISTS "Public write access" ON email_campaigns;
\nDROP POLICY IF EXISTS "Public read access" ON email_sends;
\nDROP POLICY IF EXISTS "Public write access" ON email_sends;
\nDROP POLICY IF EXISTS "Public read access" ON email_events;
\nDROP POLICY IF EXISTS "Public write access" ON email_events;
\n\n-- Drop the old profile insert policy (will be recreated if doesn't exist)\nDROP POLICY IF EXISTS "Users can insert own profile" ON profiles;
\nDROP POLICY IF EXISTS "Users can read own profile" ON profiles;
\nDROP POLICY IF EXISTS "Users can update own profile" ON profiles;
\n\n-- Profiles table policies\nCREATE POLICY "Users can read own profile"\n  ON profiles FOR SELECT\n  TO authenticated\n  USING (auth.uid() = id);
\n\nCREATE POLICY "Users can insert own profile"\n  ON profiles FOR INSERT\n  TO authenticated\n  WITH CHECK (auth.uid() = id);
\n\nCREATE POLICY "Users can update own profile"\n  ON profiles FOR UPDATE\n  TO authenticated\n  USING (auth.uid() = id)\n  WITH CHECK (auth.uid() = id);
\n\n-- Datasets table policies\nCREATE POLICY "Users can read own datasets"\n  ON datasets FOR SELECT\n  TO authenticated\n  USING (auth.uid() = user_id);
\n\nCREATE POLICY "Users can insert own datasets"\n  ON datasets FOR INSERT\n  TO authenticated\n  WITH CHECK (auth.uid() = user_id);
\n\nCREATE POLICY "Users can update own datasets"\n  ON datasets FOR UPDATE\n  TO authenticated\n  USING (auth.uid() = user_id)\n  WITH CHECK (auth.uid() = user_id);
\n\nCREATE POLICY "Users can delete own datasets"\n  ON datasets FOR DELETE\n  TO authenticated\n  USING (auth.uid() = user_id);
\n\n-- Countries table policies (reference data - read by all authenticated users)\nCREATE POLICY "Authenticated users can read countries"\n  ON countries FOR SELECT\n  TO authenticated\n  USING (true);
\n\n-- Leads table policies\nCREATE POLICY "Users can read own leads"\n  ON leads FOR SELECT\n  TO authenticated\n  USING (\n    auth.uid() = owner_user_id OR\n    EXISTS (\n      SELECT 1 FROM datasets\n      WHERE datasets.id = leads.dataset_id\n      AND datasets.user_id = auth.uid()\n    )\n  );
\n\nCREATE POLICY "Users can insert own leads"\n  ON leads FOR INSERT\n  TO authenticated\n  WITH CHECK (\n    auth.uid() = owner_user_id OR\n    EXISTS (\n      SELECT 1 FROM datasets\n      WHERE datasets.id = leads.dataset_id\n      AND datasets.user_id = auth.uid()\n    )\n  );
\n\nCREATE POLICY "Users can update own leads"\n  ON leads FOR UPDATE\n  TO authenticated\n  USING (\n    auth.uid() = owner_user_id OR\n    EXISTS (\n      SELECT 1 FROM datasets\n      WHERE datasets.id = leads.dataset_id\n      AND datasets.user_id = auth.uid()\n    )\n  )\n  WITH CHECK (\n    auth.uid() = owner_user_id OR\n    EXISTS (\n      SELECT 1 FROM datasets\n      WHERE datasets.id = leads.dataset_id\n      AND datasets.user_id = auth.uid()\n    )\n  );
\n\nCREATE POLICY "Users can delete own leads"\n  ON leads FOR DELETE\n  TO authenticated\n  USING (\n    auth.uid() = owner_user_id OR\n    EXISTS (\n      SELECT 1 FROM datasets\n      WHERE datasets.id = leads.dataset_id\n      AND datasets.user_id = auth.uid()\n    )\n  );
\n\n-- Activities table policies\nCREATE POLICY "Users can read own activities"\n  ON activities FOR SELECT\n  TO authenticated\n  USING (auth.uid() = created_by);
\n\nCREATE POLICY "Users can insert own activities"\n  ON activities FOR INSERT\n  TO authenticated\n  WITH CHECK (auth.uid() = created_by);
\n\nCREATE POLICY "Users can update own activities"\n  ON activities FOR UPDATE\n  TO authenticated\n  USING (auth.uid() = created_by)\n  WITH CHECK (auth.uid() = created_by);
\n\nCREATE POLICY "Users can delete own activities"\n  ON activities FOR DELETE\n  TO authenticated\n  USING (auth.uid() = created_by);
\n\n-- Email templates table policies\nCREATE POLICY "Users can read own email templates"\n  ON email_templates FOR SELECT\n  TO authenticated\n  USING (auth.uid() = user_id);
\n\nCREATE POLICY "Users can insert own email templates"\n  ON email_templates FOR INSERT\n  TO authenticated\n  WITH CHECK (auth.uid() = user_id);
\n\nCREATE POLICY "Users can update own email templates"\n  ON email_templates FOR UPDATE\n  TO authenticated\n  USING (auth.uid() = user_id)\n  WITH CHECK (auth.uid() = user_id);
\n\nCREATE POLICY "Users can delete own email templates"\n  ON email_templates FOR DELETE\n  TO authenticated\n  USING (auth.uid() = user_id);
\n\n-- Email campaigns table policies\nCREATE POLICY "Users can read own email campaigns"\n  ON email_campaigns FOR SELECT\n  TO authenticated\n  USING (auth.uid() = created_by);
\n\nCREATE POLICY "Users can insert own email campaigns"\n  ON email_campaigns FOR INSERT\n  TO authenticated\n  WITH CHECK (auth.uid() = created_by);
\n\nCREATE POLICY "Users can update own email campaigns"\n  ON email_campaigns FOR UPDATE\n  TO authenticated\n  USING (auth.uid() = created_by)\n  WITH CHECK (auth.uid() = created_by);
\n\nCREATE POLICY "Users can delete own email campaigns"\n  ON email_campaigns FOR DELETE\n  TO authenticated\n  USING (auth.uid() = created_by);
\n\n-- Email sends table policies\nCREATE POLICY "Users can read own email sends"\n  ON email_sends FOR SELECT\n  TO authenticated\n  USING (\n    EXISTS (\n      SELECT 1 FROM email_campaigns\n      WHERE email_campaigns.id = email_sends.campaign_id\n      AND email_campaigns.created_by = auth.uid()\n    )\n  );
\n\nCREATE POLICY "System can insert email sends"\n  ON email_sends FOR INSERT\n  TO authenticated\n  WITH CHECK (\n    EXISTS (\n      SELECT 1 FROM email_campaigns\n      WHERE email_campaigns.id = email_sends.campaign_id\n      AND email_campaigns.created_by = auth.uid()\n    )\n  );
\n\nCREATE POLICY "System can update email sends"\n  ON email_sends FOR UPDATE\n  TO authenticated\n  USING (\n    EXISTS (\n      SELECT 1 FROM email_campaigns\n      WHERE email_campaigns.id = email_sends.campaign_id\n      AND email_campaigns.created_by = auth.uid()\n    )\n  )\n  WITH CHECK (\n    EXISTS (\n      SELECT 1 FROM email_campaigns\n      WHERE email_campaigns.id = email_sends.campaign_id\n      AND email_campaigns.created_by = auth.uid()\n    )\n  );
\n\n-- Email events table policies\nCREATE POLICY "Users can read own email events"\n  ON email_events FOR SELECT\n  TO authenticated\n  USING (\n    EXISTS (\n      SELECT 1 FROM email_sends\n      JOIN email_campaigns ON email_campaigns.id = email_sends.campaign_id\n      WHERE email_sends.id = email_events.send_id\n      AND email_campaigns.created_by = auth.uid()\n    )\n  );
\n\nCREATE POLICY "System can insert email events"\n  ON email_events FOR INSERT\n  TO authenticated\n  WITH CHECK (true);
\n\nCREATE POLICY "System can update email events"\n  ON email_events FOR UPDATE\n  TO authenticated\n  USING (true)\n  WITH CHECK (true);
;
