/*\n  # Add Make.com Integration Support\n\n  1. Table Updates\n    - Extend `email_campaigns` with additional fields:\n      - `from_name` (text) - Sender name\n      - `from_email` (text) - Sender email address\n      - `reply_to` (text) - Reply-to email address\n      - `preview_text` (text) - Email preview/preheader text\n      - `last_triggered_at` (timestamptz) - Last webhook trigger time\n      - Update status enum to include 'queued' and 'paused'\n\n    - Extend `email_sends` with additional fields:\n      - `to_email` (text) - Actual recipient email address\n      - `provider` (text) - Email provider used (default 'make')\n      - `queued_at` (timestamptz) - When email was queued\n      - `updated_at` (timestamptz) - Last update timestamp\n      - Update status enum to include 'sending' and 'skipped'\n\n  2. New Table\n    - `unsubscribe_tokens`\n      - `token` (text, primary key) - Unique unsubscribe token\n      - `lead_id` (uuid) - Foreign key to leads\n      - `campaign_id` (uuid, nullable) - Foreign key to email_campaigns\n      - `created_at` (timestamptz) - Token creation time\n      - `used_at` (timestamptz, nullable) - Token usage time\n      - `expires_at` (timestamptz, nullable) - Token expiration time\n\n  3. Indexes\n    - Index on email_sends(campaign_id, status) for queue queries\n    - Index on email_sends(to_email) for lookup\n    - Index on unsubscribe_tokens(lead_id)\n\n  4. Security\n    - Enable RLS on unsubscribe_tokens\n    - Add public read policy for unsubscribe validation\n    - Add service role write policy\n*/\n\n-- Update email_campaigns status constraint\nDO $$\nBEGIN\n  IF EXISTS (\n    SELECT 1 FROM information_schema.constraint_column_usage\n    WHERE table_name = 'email_campaigns' AND constraint_name LIKE '%status%check%'\n  ) THEN\n    ALTER TABLE email_campaigns DROP CONSTRAINT IF EXISTS email_campaigns_status_check;
\n  END IF;
\nEND $$;
\n\nALTER TABLE email_campaigns\n  ADD CONSTRAINT email_campaigns_status_check\n  CHECK (status IN ('draft', 'queued', 'sending', 'sent', 'paused', 'failed'));
\n\n-- Add new columns to email_campaigns\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'email_campaigns' AND column_name = 'from_name'\n  ) THEN\n    ALTER TABLE email_campaigns ADD COLUMN from_name text;
\n  END IF;
\n\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'email_campaigns' AND column_name = 'from_email'\n  ) THEN\n    ALTER TABLE email_campaigns ADD COLUMN from_email text;
\n  END IF;
\n\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'email_campaigns' AND column_name = 'reply_to'\n  ) THEN\n    ALTER TABLE email_campaigns ADD COLUMN reply_to text;
\n  END IF;
\n\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'email_campaigns' AND column_name = 'preview_text'\n  ) THEN\n    ALTER TABLE email_campaigns ADD COLUMN preview_text text;
\n  END IF;
\n\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'email_campaigns' AND column_name = 'last_triggered_at'\n  ) THEN\n    ALTER TABLE email_campaigns ADD COLUMN last_triggered_at timestamptz;
\n  END IF;
\nEND $$;
\n\n-- Update email_sends status constraint\nDO $$\nBEGIN\n  IF EXISTS (\n    SELECT 1 FROM information_schema.constraint_column_usage\n    WHERE table_name = 'email_sends' AND constraint_name LIKE '%status%check%'\n  ) THEN\n    ALTER TABLE email_sends DROP CONSTRAINT IF EXISTS email_sends_status_check;
\n  END IF;
\nEND $$;
\n\nALTER TABLE email_sends\n  ADD CONSTRAINT email_sends_status_check\n  CHECK (status IN ('queued', 'sending', 'sent', 'delivered', 'failed', 'bounced', 'skipped'));
\n\n-- Add new columns to email_sends\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'email_sends' AND column_name = 'to_email'\n  ) THEN\n    ALTER TABLE email_sends ADD COLUMN to_email text;
\n  END IF;
\n\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'email_sends' AND column_name = 'provider'\n  ) THEN\n    ALTER TABLE email_sends ADD COLUMN provider text DEFAULT 'make';
\n  END IF;
\n\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'email_sends' AND column_name = 'queued_at'\n  ) THEN\n    ALTER TABLE email_sends ADD COLUMN queued_at timestamptz DEFAULT now();
\n  END IF;
\n\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'email_sends' AND column_name = 'updated_at'\n  ) THEN\n    ALTER TABLE email_sends ADD COLUMN updated_at timestamptz DEFAULT now();
\n  END IF;
\nEND $$;
\n\n-- Create unsubscribe_tokens table\nCREATE TABLE IF NOT EXISTS unsubscribe_tokens (\n  token text PRIMARY KEY,\n  lead_id uuid REFERENCES leads(id) ON DELETE CASCADE,\n  campaign_id uuid REFERENCES email_campaigns(id) ON DELETE SET NULL,\n  created_at timestamptz DEFAULT now(),\n  used_at timestamptz,\n  expires_at timestamptz\n);
\n\n-- Create indexes for performance\nCREATE INDEX IF NOT EXISTS idx_email_sends_campaign_status ON email_sends(campaign_id, status);
\nCREATE INDEX IF NOT EXISTS idx_email_sends_to_email ON email_sends(to_email);
\nCREATE INDEX IF NOT EXISTS idx_unsubscribe_tokens_lead_id ON unsubscribe_tokens(lead_id);
\n\n-- Enable RLS on unsubscribe_tokens\nALTER TABLE unsubscribe_tokens ENABLE ROW LEVEL SECURITY;
\n\n-- RLS Policies for unsubscribe_tokens\nCREATE POLICY "Anyone can read unsubscribe tokens"\n  ON unsubscribe_tokens FOR SELECT\n  TO anon, authenticated\n  USING (true);
\n\nCREATE POLICY "Service role can insert unsubscribe tokens"\n  ON unsubscribe_tokens FOR INSERT\n  TO authenticated\n  WITH CHECK (true);
\n\nCREATE POLICY "Service role can update unsubscribe tokens"\n  ON unsubscribe_tokens FOR UPDATE\n  TO authenticated\n  USING (true)\n  WITH CHECK (true);
\n\n-- Create function to update updated_at timestamp\nCREATE OR REPLACE FUNCTION update_email_sends_updated_at()\nRETURNS TRIGGER AS $$\nBEGIN\n  NEW.updated_at = now();
\n  RETURN NEW;
\nEND;
\n$$ LANGUAGE plpgsql;
\n\n-- Create trigger for email_sends updated_at\nDROP TRIGGER IF EXISTS email_sends_updated_at_trigger ON email_sends;
\nCREATE TRIGGER email_sends_updated_at_trigger\n  BEFORE UPDATE ON email_sends\n  FOR EACH ROW\n  EXECUTE FUNCTION update_email_sends_updated_at();
\n;
