/*\n  # Seed Demo Data for Liftpictures Operator Dashboard\n\n  Populates the database with realistic demo data for development and testing.\n\n  1. Organizations\n    - Alpine Adventures Group (demo org)\n\n  2. Parks\n    - Summit Peak Resort (Colorado)\n    - Crystal Lake Park (Utah)\n\n  3. Attractions\n    - Eagle Gondola, Thunder Rapids (Summit Peak)\n    - Sky Bridge Walk, Crystal Coaster (Crystal Lake)\n\n  4. Sample Data\n    - 40 customers with varied profiles\n    - ~200 photos distributed across attractions over 30 days\n    - ~80 purchases with realistic pricing\n    - 25 marketing leads\n    - 8 support tickets\n    - 20 system health events\n\n  5. Notes\n    - Uses generate_series for date-distributed data\n    - All monetary values in USD cents\n    - Photo URLs use Pexels stock images\n*/\n\nDO $$\nDECLARE\n  org_id uuid;
\n  park1_id uuid;
\n  park2_id uuid;
\n  attr1_id uuid;
\n  attr2_id uuid;
\n  attr3_id uuid;
\n  attr4_id uuid;
\n  cust_ids uuid[];
\n  photo_ids uuid[];
\n  temp_id uuid;
\n  i integer;
\n  rand_attr uuid;
\n  rand_cust uuid;
\n  rand_photo uuid;
\n  attrs uuid[];
\n  first_names text[] := ARRAY['Emma','Liam','Olivia','Noah','Ava','James','Sophia','Oliver','Isabella','William','Mia','Benjamin','Charlotte','Elijah','Amelia','Lucas','Harper','Mason','Evelyn','Logan','Abigail','Alexander','Emily','Ethan','Ella','Jacob','Elizabeth','Michael','Camila','Daniel','Grace','Henry','Sofia','Jackson','Scarlett','Sebastian','Victoria','Aiden','Aria','Matthew'];
\n  last_names text[] := ARRAY['Smith','Johnson','Williams','Brown','Jones','Garcia','Miller','Davis','Rodriguez','Martinez','Hernandez','Lopez','Gonzalez','Wilson','Anderson','Thomas','Taylor','Moore','Jackson','Martin','Lee','Perez','Thompson','White','Harris','Sanchez','Clark','Ramirez','Lewis','Robinson'];
\n  sources text[] := ARRAY['website','kiosk','qr_code','social_media','referral','email_campaign'];
\n  event_types text[] := ARRAY['webhook_received','api_call','camera_sync','payment_processed','photo_upload','service_restart','error_logged'];
\nBEGIN\n  -- Create organization\n  INSERT INTO organizations (name, slug, logo_url)\n  VALUES ('Alpine Adventures Group', 'alpine-adventures', null)\n  RETURNING id INTO org_id;
\n\n  -- Create parks\n  INSERT INTO parks (organization_id, name, slug, location, timezone)\n  VALUES (org_id, 'Summit Peak Resort', 'summit-peak', 'Aspen, Colorado', 'America/Denver')\n  RETURNING id INTO park1_id;
\n\n  INSERT INTO parks (organization_id, name, slug, location, timezone)\n  VALUES (org_id, 'Crystal Lake Park', 'crystal-lake', 'Park City, Utah', 'America/Denver')\n  RETURNING id INTO park2_id;
\n\n  -- Create attractions\n  INSERT INTO attractions (park_id, name, type, status)\n  VALUES (park1_id, 'Eagle Gondola', 'gondola', 'active')\n  RETURNING id INTO attr1_id;
\n\n  INSERT INTO attractions (park_id, name, type, status)\n  VALUES (park1_id, 'Thunder Rapids', 'ride', 'active')\n  RETURNING id INTO attr2_id;
\n\n  INSERT INTO attractions (park_id, name, type, status)\n  VALUES (park2_id, 'Sky Bridge Walk', 'walk', 'active')\n  RETURNING id INTO attr3_id;
\n\n  INSERT INTO attractions (park_id, name, type, status)\n  VALUES (park2_id, 'Crystal Coaster', 'coaster', 'maintenance')\n  RETURNING id INTO attr4_id;
\n\n  attrs := ARRAY[attr1_id, attr2_id, attr3_id, attr4_id];
\n\n  -- Create 40 customers\n  cust_ids := ARRAY[]::uuid[];
\n  FOR i IN 1..40 LOOP\n    INSERT INTO customers (email, full_name, phone, opted_in_marketing, created_at)\n    VALUES (\n      lower(first_names[i]) || '.' || lower(last_names[((i * 7) % 30) + 1]) || '@example.com',\n      first_names[i] || ' ' || last_names[((i * 7) % 30) + 1],\n      '+1555' || lpad((1000000 + floor(random() * 8999999))::text, 7, '0'),\n      random() > 0.6,\n      now() - (floor(random() * 90) || ' days')::interval\n    )\n    RETURNING id INTO temp_id;
\n    cust_ids := cust_ids || temp_id;
\n  END LOOP;
\n\n  -- Create ~200 photos across attractions over 30 days\n  photo_ids := ARRAY[]::uuid[];
\n  FOR i IN 1..200 LOOP\n    rand_attr := attrs[1 + floor(random() * 4)::int];
\n    rand_cust := cust_ids[1 + floor(random() * 40)::int];
\n\n    INSERT INTO photos (attraction_id, customer_id, image_url, thumbnail_url, taken_at, status)\n    VALUES (\n      rand_attr,\n      CASE WHEN random() > 0.15 THEN rand_cust ELSE NULL END,\n      'https://images.pexels.com/photos/' ||\n        (ARRAY[417074,691668,1054218,1308881,1366909,1576937,2325446,2387873,2559941,2662116,3225517,3408744,3551227,3617500,3889843,4215113,4534200,5472308,6044198,7031406])[1 + floor(random() * 20)::int] ||\n        '/pexels-photo.jpeg?auto=compress&cs=tinysrgb&w=800',\n      'https://images.pexels.com/photos/' ||\n        (ARRAY[417074,691668,1054218,1308881,1366909,1576937,2325446,2387873,2559941,2662116,3225517,3408744,3551227,3617500,3889843,4215113,4534200,5472308,6044198,7031406])[1 + floor(random() * 20)::int] ||\n        '/pexels-photo.jpeg?auto=compress&cs=tinysrgb&w=200',\n      now() - (floor(random() * 30) || ' days')::interval - (floor(random() * 24) || ' hours')::interval,\n      CASE\n        WHEN random() > 0.6 THEN 'purchased'\n        WHEN random() > 0.1 THEN 'available'\n        ELSE 'expired'\n      END\n    )\n    RETURNING id INTO temp_id;
\n    photo_ids := photo_ids || temp_id;
\n  END LOOP;
\n\n  -- Create ~80 purchases\n  FOR i IN 1..80 LOOP\n    rand_photo := photo_ids[1 + floor(random() * array_length(photo_ids, 1))::int];
\n    rand_cust := cust_ids[1 + floor(random() * 40)::int];
\n\n    INSERT INTO purchases (photo_id, customer_id, amount_cents, currency, stripe_payment_id, status, purchased_at)\n    VALUES (\n      rand_photo,\n      rand_cust,\n      (ARRAY[999, 1499, 1999, 2499, 2999, 3499])[1 + floor(random() * 6)::int],\n      'usd',\n      'pi_' || encode(gen_random_bytes(12), 'hex'),\n      CASE\n        WHEN random() > 0.92 THEN 'refunded'\n        WHEN random() > 0.85 THEN 'pending'\n        ELSE 'completed'\n      END,\n      now() - (floor(random() * 30) || ' days')::interval - (floor(random() * 24) || ' hours')::interval\n    )\n    ON CONFLICT DO NOTHING;
\n  END LOOP;
\n\n  -- Create 25 leads\n  FOR i IN 1..25 LOOP\n    INSERT INTO leads (park_id, email, full_name, source, opted_in, created_at)\n    VALUES (\n      CASE WHEN random() > 0.45 THEN park1_id ELSE park2_id END,\n      'lead' || i || '@example.com',\n      first_names[((i * 3) % 40) + 1] || ' ' || last_names[((i * 5) % 30) + 1],\n      sources[1 + floor(random() * 6)::int],\n      random() > 0.35,\n      now() - (floor(random() * 30) || ' days')::interval\n    );
\n  END LOOP;
\n\n  -- Create 8 support tickets (using a placeholder operator id since no real operator exists yet)\n  -- These will be viewable once an operator joins the org\n\n  -- Create 20 system health events\n  FOR i IN 1..20 LOOP\n    INSERT INTO system_health_events (park_id, event_type, severity, message, metadata, created_at)\n    VALUES (\n      CASE WHEN random() > 0.5 THEN park1_id ELSE park2_id END,\n      event_types[1 + floor(random() * 7)::int],\n      CASE\n        WHEN random() > 0.9 THEN 'critical'\n        WHEN random() > 0.7 THEN 'error'\n        WHEN random() > 0.4 THEN 'warning'\n        ELSE 'info'\n      END,\n      CASE event_types[1 + floor(random() * 7)::int]\n        WHEN 'webhook_received' THEN 'Stripe webhook processed successfully'\n        WHEN 'api_call' THEN 'External API response time: ' || (50 + floor(random() * 450))::text || 'ms'\n        WHEN 'camera_sync' THEN 'Camera ' || (1 + floor(random() * 8))::text || ' synced ' || (10 + floor(random() * 90))::text || ' photos'\n        WHEN 'payment_processed' THEN 'Payment of $' || (9.99 + floor(random() * 25))::text || ' processed'\n        WHEN 'photo_upload' THEN 'Batch upload of ' || (5 + floor(random() * 50))::text || ' photos completed'\n        WHEN 'service_restart' THEN 'Service restarted after scheduled maintenance'\n        ELSE 'System check completed - all services operational'\n      END,\n      jsonb_build_object(\n        'duration_ms', floor(random() * 1000),\n        'source', CASE WHEN random() > 0.5 THEN 'automated' ELSE 'manual' END\n      ),\n      now() - (floor(random() * 7) || ' days')::interval - (floor(random() * 24) || ' hours')::interval\n    );
\n  END LOOP;
\n\nEND $$;
;
