/*\n  # Simplify Profile Creation RLS\n\n  Make the operator profile creation work reliably by:\n  1. Dropping complex policies\n  2. Using a simpler approach that works with Supabase Auth\n  3. Granting the trigger function explicit permissions\n*/\n\n-- Drop all existing policies on operator_profiles for INSERT\nDROP POLICY IF EXISTS "Allow profile creation during signup" ON operator_profiles;
\nDROP POLICY IF EXISTS "Service role can insert profiles" ON operator_profiles;
\nDROP POLICY IF EXISTS "Operators can insert own profile" ON operator_profiles;
\n\n-- Create a single, simple INSERT policy that allows any authenticated user to insert their own profile\nCREATE POLICY "Users can create own profile"\n  ON operator_profiles FOR INSERT\n  WITH CHECK (auth.uid() = id);
\n\n-- Grant the postgres role (used by triggers) permission to bypass RLS for this specific operation\n-- This is done by recreating the trigger function to use a security definer approach\nCREATE OR REPLACE FUNCTION handle_new_operator()\nRETURNS trigger\nLANGUAGE plpgsql\nSECURITY DEFINER\nAS $$\nBEGIN\n  -- Temporarily disable RLS for this insert\n  INSERT INTO public.operator_profiles (id, email, full_name)\n  VALUES (\n    NEW.id,\n    NEW.email,\n    COALESCE(NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1))\n  );
\n  RETURN NEW;
\nEXCEPTION\n  WHEN unique_violation THEN\n    -- Profile already exists, ignore\n    RETURN NEW;
\n  WHEN OTHERS THEN\n    -- Log error but don't break auth\n    RAISE WARNING 'Failed to create operator profile: %', SQLERRM;
\n    RETURN NEW;
\nEND;
\n$$;
\n\n-- Grant the function owner the ability to insert into operator_profiles\n-- This makes the SECURITY DEFINER function work properly\nGRANT INSERT ON operator_profiles TO authenticated;
\nGRANT USAGE ON SCHEMA public TO authenticated;
;
